// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/ordering-backend/internal/ent/auditlog"
	"github.com/bengobox/ordering-backend/internal/ent/predicate"
	"github.com/google/uuid"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (alu *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	alu.mutation.Where(ps...)
	return alu
}

// SetTenantID sets the "tenant_id" field.
func (alu *AuditLogUpdate) SetTenantID(u uuid.UUID) *AuditLogUpdate {
	alu.mutation.SetTenantID(u)
	return alu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableTenantID(u *uuid.UUID) *AuditLogUpdate {
	if u != nil {
		alu.SetTenantID(*u)
	}
	return alu
}

// ClearTenantID clears the value of the "tenant_id" field.
func (alu *AuditLogUpdate) ClearTenantID() *AuditLogUpdate {
	alu.mutation.ClearTenantID()
	return alu
}

// SetUserID sets the "user_id" field.
func (alu *AuditLogUpdate) SetUserID(u uuid.UUID) *AuditLogUpdate {
	alu.mutation.SetUserID(u)
	return alu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableUserID(u *uuid.UUID) *AuditLogUpdate {
	if u != nil {
		alu.SetUserID(*u)
	}
	return alu
}

// ClearUserID clears the value of the "user_id" field.
func (alu *AuditLogUpdate) ClearUserID() *AuditLogUpdate {
	alu.mutation.ClearUserID()
	return alu
}

// SetAction sets the "action" field.
func (alu *AuditLogUpdate) SetAction(s string) *AuditLogUpdate {
	alu.mutation.SetAction(s)
	return alu
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableAction(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetAction(*s)
	}
	return alu
}

// SetResourceType sets the "resource_type" field.
func (alu *AuditLogUpdate) SetResourceType(s string) *AuditLogUpdate {
	alu.mutation.SetResourceType(s)
	return alu
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableResourceType(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetResourceType(*s)
	}
	return alu
}

// ClearResourceType clears the value of the "resource_type" field.
func (alu *AuditLogUpdate) ClearResourceType() *AuditLogUpdate {
	alu.mutation.ClearResourceType()
	return alu
}

// SetResourceID sets the "resource_id" field.
func (alu *AuditLogUpdate) SetResourceID(s string) *AuditLogUpdate {
	alu.mutation.SetResourceID(s)
	return alu
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableResourceID(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetResourceID(*s)
	}
	return alu
}

// ClearResourceID clears the value of the "resource_id" field.
func (alu *AuditLogUpdate) ClearResourceID() *AuditLogUpdate {
	alu.mutation.ClearResourceID()
	return alu
}

// SetHTTPMethod sets the "http_method" field.
func (alu *AuditLogUpdate) SetHTTPMethod(s string) *AuditLogUpdate {
	alu.mutation.SetHTTPMethod(s)
	return alu
}

// SetNillableHTTPMethod sets the "http_method" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableHTTPMethod(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetHTTPMethod(*s)
	}
	return alu
}

// ClearHTTPMethod clears the value of the "http_method" field.
func (alu *AuditLogUpdate) ClearHTTPMethod() *AuditLogUpdate {
	alu.mutation.ClearHTTPMethod()
	return alu
}

// SetPath sets the "path" field.
func (alu *AuditLogUpdate) SetPath(s string) *AuditLogUpdate {
	alu.mutation.SetPath(s)
	return alu
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillablePath(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetPath(*s)
	}
	return alu
}

// ClearPath clears the value of the "path" field.
func (alu *AuditLogUpdate) ClearPath() *AuditLogUpdate {
	alu.mutation.ClearPath()
	return alu
}

// SetStatusCode sets the "status_code" field.
func (alu *AuditLogUpdate) SetStatusCode(i int) *AuditLogUpdate {
	alu.mutation.ResetStatusCode()
	alu.mutation.SetStatusCode(i)
	return alu
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableStatusCode(i *int) *AuditLogUpdate {
	if i != nil {
		alu.SetStatusCode(*i)
	}
	return alu
}

// AddStatusCode adds i to the "status_code" field.
func (alu *AuditLogUpdate) AddStatusCode(i int) *AuditLogUpdate {
	alu.mutation.AddStatusCode(i)
	return alu
}

// ClearStatusCode clears the value of the "status_code" field.
func (alu *AuditLogUpdate) ClearStatusCode() *AuditLogUpdate {
	alu.mutation.ClearStatusCode()
	return alu
}

// SetIPAddress sets the "ip_address" field.
func (alu *AuditLogUpdate) SetIPAddress(s string) *AuditLogUpdate {
	alu.mutation.SetIPAddress(s)
	return alu
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableIPAddress(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetIPAddress(*s)
	}
	return alu
}

// ClearIPAddress clears the value of the "ip_address" field.
func (alu *AuditLogUpdate) ClearIPAddress() *AuditLogUpdate {
	alu.mutation.ClearIPAddress()
	return alu
}

// SetUserAgent sets the "user_agent" field.
func (alu *AuditLogUpdate) SetUserAgent(s string) *AuditLogUpdate {
	alu.mutation.SetUserAgent(s)
	return alu
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableUserAgent(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetUserAgent(*s)
	}
	return alu
}

// ClearUserAgent clears the value of the "user_agent" field.
func (alu *AuditLogUpdate) ClearUserAgent() *AuditLogUpdate {
	alu.mutation.ClearUserAgent()
	return alu
}

// SetRequestBody sets the "request_body" field.
func (alu *AuditLogUpdate) SetRequestBody(m map[string]interface{}) *AuditLogUpdate {
	alu.mutation.SetRequestBody(m)
	return alu
}

// ClearRequestBody clears the value of the "request_body" field.
func (alu *AuditLogUpdate) ClearRequestBody() *AuditLogUpdate {
	alu.mutation.ClearRequestBody()
	return alu
}

// SetContext sets the "context" field.
func (alu *AuditLogUpdate) SetContext(m map[string]interface{}) *AuditLogUpdate {
	alu.mutation.SetContext(m)
	return alu
}

// ClearContext clears the value of the "context" field.
func (alu *AuditLogUpdate) ClearContext() *AuditLogUpdate {
	alu.mutation.ClearContext()
	return alu
}

// SetDurationMs sets the "duration_ms" field.
func (alu *AuditLogUpdate) SetDurationMs(i int64) *AuditLogUpdate {
	alu.mutation.ResetDurationMs()
	alu.mutation.SetDurationMs(i)
	return alu
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableDurationMs(i *int64) *AuditLogUpdate {
	if i != nil {
		alu.SetDurationMs(*i)
	}
	return alu
}

// AddDurationMs adds i to the "duration_ms" field.
func (alu *AuditLogUpdate) AddDurationMs(i int64) *AuditLogUpdate {
	alu.mutation.AddDurationMs(i)
	return alu
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (alu *AuditLogUpdate) ClearDurationMs() *AuditLogUpdate {
	alu.mutation.ClearDurationMs()
	return alu
}

// Mutation returns the AuditLogMutation object of the builder.
func (alu *AuditLogUpdate) Mutation() *AuditLogMutation {
	return alu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (alu *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, alu.sqlSave, alu.mutation, alu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (alu *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := alu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (alu *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := alu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alu *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := alu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (alu *AuditLogUpdate) check() error {
	if v, ok := alu.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := alu.mutation.IPAddress(); ok {
		if err := auditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "AuditLog.ip_address": %w`, err)}
		}
	}
	if v, ok := alu.mutation.UserAgent(); ok {
		if err := auditlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuditLog.user_agent": %w`, err)}
		}
	}
	return nil
}

func (alu *AuditLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := alu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	if ps := alu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := alu.mutation.TenantID(); ok {
		_spec.SetField(auditlog.FieldTenantID, field.TypeUUID, value)
	}
	if alu.mutation.TenantIDCleared() {
		_spec.ClearField(auditlog.FieldTenantID, field.TypeUUID)
	}
	if value, ok := alu.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeUUID, value)
	}
	if alu.mutation.UserIDCleared() {
		_spec.ClearField(auditlog.FieldUserID, field.TypeUUID)
	}
	if value, ok := alu.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := alu.mutation.ResourceType(); ok {
		_spec.SetField(auditlog.FieldResourceType, field.TypeString, value)
	}
	if alu.mutation.ResourceTypeCleared() {
		_spec.ClearField(auditlog.FieldResourceType, field.TypeString)
	}
	if value, ok := alu.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeString, value)
	}
	if alu.mutation.ResourceIDCleared() {
		_spec.ClearField(auditlog.FieldResourceID, field.TypeString)
	}
	if value, ok := alu.mutation.HTTPMethod(); ok {
		_spec.SetField(auditlog.FieldHTTPMethod, field.TypeString, value)
	}
	if alu.mutation.HTTPMethodCleared() {
		_spec.ClearField(auditlog.FieldHTTPMethod, field.TypeString)
	}
	if value, ok := alu.mutation.Path(); ok {
		_spec.SetField(auditlog.FieldPath, field.TypeString, value)
	}
	if alu.mutation.PathCleared() {
		_spec.ClearField(auditlog.FieldPath, field.TypeString)
	}
	if value, ok := alu.mutation.StatusCode(); ok {
		_spec.SetField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := alu.mutation.AddedStatusCode(); ok {
		_spec.AddField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if alu.mutation.StatusCodeCleared() {
		_spec.ClearField(auditlog.FieldStatusCode, field.TypeInt)
	}
	if value, ok := alu.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if alu.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := alu.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if alu.mutation.UserAgentCleared() {
		_spec.ClearField(auditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := alu.mutation.RequestBody(); ok {
		_spec.SetField(auditlog.FieldRequestBody, field.TypeJSON, value)
	}
	if alu.mutation.RequestBodyCleared() {
		_spec.ClearField(auditlog.FieldRequestBody, field.TypeJSON)
	}
	if value, ok := alu.mutation.Context(); ok {
		_spec.SetField(auditlog.FieldContext, field.TypeJSON, value)
	}
	if alu.mutation.ContextCleared() {
		_spec.ClearField(auditlog.FieldContext, field.TypeJSON)
	}
	if value, ok := alu.mutation.DurationMs(); ok {
		_spec.SetField(auditlog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := alu.mutation.AddedDurationMs(); ok {
		_spec.AddField(auditlog.FieldDurationMs, field.TypeInt64, value)
	}
	if alu.mutation.DurationMsCleared() {
		_spec.ClearField(auditlog.FieldDurationMs, field.TypeInt64)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, alu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	alu.mutation.done = true
	return n, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetTenantID sets the "tenant_id" field.
func (aluo *AuditLogUpdateOne) SetTenantID(u uuid.UUID) *AuditLogUpdateOne {
	aluo.mutation.SetTenantID(u)
	return aluo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableTenantID(u *uuid.UUID) *AuditLogUpdateOne {
	if u != nil {
		aluo.SetTenantID(*u)
	}
	return aluo
}

// ClearTenantID clears the value of the "tenant_id" field.
func (aluo *AuditLogUpdateOne) ClearTenantID() *AuditLogUpdateOne {
	aluo.mutation.ClearTenantID()
	return aluo
}

// SetUserID sets the "user_id" field.
func (aluo *AuditLogUpdateOne) SetUserID(u uuid.UUID) *AuditLogUpdateOne {
	aluo.mutation.SetUserID(u)
	return aluo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableUserID(u *uuid.UUID) *AuditLogUpdateOne {
	if u != nil {
		aluo.SetUserID(*u)
	}
	return aluo
}

// ClearUserID clears the value of the "user_id" field.
func (aluo *AuditLogUpdateOne) ClearUserID() *AuditLogUpdateOne {
	aluo.mutation.ClearUserID()
	return aluo
}

// SetAction sets the "action" field.
func (aluo *AuditLogUpdateOne) SetAction(s string) *AuditLogUpdateOne {
	aluo.mutation.SetAction(s)
	return aluo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableAction(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetAction(*s)
	}
	return aluo
}

// SetResourceType sets the "resource_type" field.
func (aluo *AuditLogUpdateOne) SetResourceType(s string) *AuditLogUpdateOne {
	aluo.mutation.SetResourceType(s)
	return aluo
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableResourceType(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetResourceType(*s)
	}
	return aluo
}

// ClearResourceType clears the value of the "resource_type" field.
func (aluo *AuditLogUpdateOne) ClearResourceType() *AuditLogUpdateOne {
	aluo.mutation.ClearResourceType()
	return aluo
}

// SetResourceID sets the "resource_id" field.
func (aluo *AuditLogUpdateOne) SetResourceID(s string) *AuditLogUpdateOne {
	aluo.mutation.SetResourceID(s)
	return aluo
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableResourceID(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetResourceID(*s)
	}
	return aluo
}

// ClearResourceID clears the value of the "resource_id" field.
func (aluo *AuditLogUpdateOne) ClearResourceID() *AuditLogUpdateOne {
	aluo.mutation.ClearResourceID()
	return aluo
}

// SetHTTPMethod sets the "http_method" field.
func (aluo *AuditLogUpdateOne) SetHTTPMethod(s string) *AuditLogUpdateOne {
	aluo.mutation.SetHTTPMethod(s)
	return aluo
}

// SetNillableHTTPMethod sets the "http_method" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableHTTPMethod(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetHTTPMethod(*s)
	}
	return aluo
}

// ClearHTTPMethod clears the value of the "http_method" field.
func (aluo *AuditLogUpdateOne) ClearHTTPMethod() *AuditLogUpdateOne {
	aluo.mutation.ClearHTTPMethod()
	return aluo
}

// SetPath sets the "path" field.
func (aluo *AuditLogUpdateOne) SetPath(s string) *AuditLogUpdateOne {
	aluo.mutation.SetPath(s)
	return aluo
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillablePath(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetPath(*s)
	}
	return aluo
}

// ClearPath clears the value of the "path" field.
func (aluo *AuditLogUpdateOne) ClearPath() *AuditLogUpdateOne {
	aluo.mutation.ClearPath()
	return aluo
}

// SetStatusCode sets the "status_code" field.
func (aluo *AuditLogUpdateOne) SetStatusCode(i int) *AuditLogUpdateOne {
	aluo.mutation.ResetStatusCode()
	aluo.mutation.SetStatusCode(i)
	return aluo
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableStatusCode(i *int) *AuditLogUpdateOne {
	if i != nil {
		aluo.SetStatusCode(*i)
	}
	return aluo
}

// AddStatusCode adds i to the "status_code" field.
func (aluo *AuditLogUpdateOne) AddStatusCode(i int) *AuditLogUpdateOne {
	aluo.mutation.AddStatusCode(i)
	return aluo
}

// ClearStatusCode clears the value of the "status_code" field.
func (aluo *AuditLogUpdateOne) ClearStatusCode() *AuditLogUpdateOne {
	aluo.mutation.ClearStatusCode()
	return aluo
}

// SetIPAddress sets the "ip_address" field.
func (aluo *AuditLogUpdateOne) SetIPAddress(s string) *AuditLogUpdateOne {
	aluo.mutation.SetIPAddress(s)
	return aluo
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableIPAddress(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetIPAddress(*s)
	}
	return aluo
}

// ClearIPAddress clears the value of the "ip_address" field.
func (aluo *AuditLogUpdateOne) ClearIPAddress() *AuditLogUpdateOne {
	aluo.mutation.ClearIPAddress()
	return aluo
}

// SetUserAgent sets the "user_agent" field.
func (aluo *AuditLogUpdateOne) SetUserAgent(s string) *AuditLogUpdateOne {
	aluo.mutation.SetUserAgent(s)
	return aluo
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableUserAgent(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetUserAgent(*s)
	}
	return aluo
}

// ClearUserAgent clears the value of the "user_agent" field.
func (aluo *AuditLogUpdateOne) ClearUserAgent() *AuditLogUpdateOne {
	aluo.mutation.ClearUserAgent()
	return aluo
}

// SetRequestBody sets the "request_body" field.
func (aluo *AuditLogUpdateOne) SetRequestBody(m map[string]interface{}) *AuditLogUpdateOne {
	aluo.mutation.SetRequestBody(m)
	return aluo
}

// ClearRequestBody clears the value of the "request_body" field.
func (aluo *AuditLogUpdateOne) ClearRequestBody() *AuditLogUpdateOne {
	aluo.mutation.ClearRequestBody()
	return aluo
}

// SetContext sets the "context" field.
func (aluo *AuditLogUpdateOne) SetContext(m map[string]interface{}) *AuditLogUpdateOne {
	aluo.mutation.SetContext(m)
	return aluo
}

// ClearContext clears the value of the "context" field.
func (aluo *AuditLogUpdateOne) ClearContext() *AuditLogUpdateOne {
	aluo.mutation.ClearContext()
	return aluo
}

// SetDurationMs sets the "duration_ms" field.
func (aluo *AuditLogUpdateOne) SetDurationMs(i int64) *AuditLogUpdateOne {
	aluo.mutation.ResetDurationMs()
	aluo.mutation.SetDurationMs(i)
	return aluo
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableDurationMs(i *int64) *AuditLogUpdateOne {
	if i != nil {
		aluo.SetDurationMs(*i)
	}
	return aluo
}

// AddDurationMs adds i to the "duration_ms" field.
func (aluo *AuditLogUpdateOne) AddDurationMs(i int64) *AuditLogUpdateOne {
	aluo.mutation.AddDurationMs(i)
	return aluo
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (aluo *AuditLogUpdateOne) ClearDurationMs() *AuditLogUpdateOne {
	aluo.mutation.ClearDurationMs()
	return aluo
}

// Mutation returns the AuditLogMutation object of the builder.
func (aluo *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return aluo.mutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (aluo *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	aluo.mutation.Where(ps...)
	return aluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aluo *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	aluo.fields = append([]string{field}, fields...)
	return aluo
}

// Save executes the query and returns the updated AuditLog entity.
func (aluo *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, aluo.sqlSave, aluo.mutation, aluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aluo *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := aluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aluo *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := aluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aluo *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := aluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aluo *AuditLogUpdateOne) check() error {
	if v, ok := aluo.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := aluo.mutation.IPAddress(); ok {
		if err := auditlog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "AuditLog.ip_address": %w`, err)}
		}
	}
	if v, ok := aluo.mutation.UserAgent(); ok {
		if err := auditlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuditLog.user_agent": %w`, err)}
		}
	}
	return nil
}

func (aluo *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := aluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	id, ok := aluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aluo.mutation.TenantID(); ok {
		_spec.SetField(auditlog.FieldTenantID, field.TypeUUID, value)
	}
	if aluo.mutation.TenantIDCleared() {
		_spec.ClearField(auditlog.FieldTenantID, field.TypeUUID)
	}
	if value, ok := aluo.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeUUID, value)
	}
	if aluo.mutation.UserIDCleared() {
		_spec.ClearField(auditlog.FieldUserID, field.TypeUUID)
	}
	if value, ok := aluo.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := aluo.mutation.ResourceType(); ok {
		_spec.SetField(auditlog.FieldResourceType, field.TypeString, value)
	}
	if aluo.mutation.ResourceTypeCleared() {
		_spec.ClearField(auditlog.FieldResourceType, field.TypeString)
	}
	if value, ok := aluo.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeString, value)
	}
	if aluo.mutation.ResourceIDCleared() {
		_spec.ClearField(auditlog.FieldResourceID, field.TypeString)
	}
	if value, ok := aluo.mutation.HTTPMethod(); ok {
		_spec.SetField(auditlog.FieldHTTPMethod, field.TypeString, value)
	}
	if aluo.mutation.HTTPMethodCleared() {
		_spec.ClearField(auditlog.FieldHTTPMethod, field.TypeString)
	}
	if value, ok := aluo.mutation.Path(); ok {
		_spec.SetField(auditlog.FieldPath, field.TypeString, value)
	}
	if aluo.mutation.PathCleared() {
		_spec.ClearField(auditlog.FieldPath, field.TypeString)
	}
	if value, ok := aluo.mutation.StatusCode(); ok {
		_spec.SetField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := aluo.mutation.AddedStatusCode(); ok {
		_spec.AddField(auditlog.FieldStatusCode, field.TypeInt, value)
	}
	if aluo.mutation.StatusCodeCleared() {
		_spec.ClearField(auditlog.FieldStatusCode, field.TypeInt)
	}
	if value, ok := aluo.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if aluo.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	if value, ok := aluo.mutation.UserAgent(); ok {
		_spec.SetField(auditlog.FieldUserAgent, field.TypeString, value)
	}
	if aluo.mutation.UserAgentCleared() {
		_spec.ClearField(auditlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := aluo.mutation.RequestBody(); ok {
		_spec.SetField(auditlog.FieldRequestBody, field.TypeJSON, value)
	}
	if aluo.mutation.RequestBodyCleared() {
		_spec.ClearField(auditlog.FieldRequestBody, field.TypeJSON)
	}
	if value, ok := aluo.mutation.Context(); ok {
		_spec.SetField(auditlog.FieldContext, field.TypeJSON, value)
	}
	if aluo.mutation.ContextCleared() {
		_spec.ClearField(auditlog.FieldContext, field.TypeJSON)
	}
	if value, ok := aluo.mutation.DurationMs(); ok {
		_spec.SetField(auditlog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := aluo.mutation.AddedDurationMs(); ok {
		_spec.AddField(auditlog.FieldDurationMs, field.TypeInt64, value)
	}
	if aluo.mutation.DurationMsCleared() {
		_spec.ClearField(auditlog.FieldDurationMs, field.TypeInt64)
	}
	_node = &AuditLog{config: aluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aluo.mutation.done = true
	return _node, nil
}
