// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/ordering-backend/internal/ent/logisticsevent"
	"github.com/google/uuid"
)

// LogisticsEventCreate is the builder for creating a LogisticsEvent entity.
type LogisticsEventCreate struct {
	config
	mutation *LogisticsEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (lec *LogisticsEventCreate) SetTenantID(u uuid.UUID) *LogisticsEventCreate {
	lec.mutation.SetTenantID(u)
	return lec
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableTenantID(u *uuid.UUID) *LogisticsEventCreate {
	if u != nil {
		lec.SetTenantID(*u)
	}
	return lec
}

// SetExternalID sets the "external_id" field.
func (lec *LogisticsEventCreate) SetExternalID(s string) *LogisticsEventCreate {
	lec.mutation.SetExternalID(s)
	return lec
}

// SetEventType sets the "event_type" field.
func (lec *LogisticsEventCreate) SetEventType(lt logisticsevent.EventType) *LogisticsEventCreate {
	lec.mutation.SetEventType(lt)
	return lec
}

// SetOrderID sets the "order_id" field.
func (lec *LogisticsEventCreate) SetOrderID(u uuid.UUID) *LogisticsEventCreate {
	lec.mutation.SetOrderID(u)
	return lec
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableOrderID(u *uuid.UUID) *LogisticsEventCreate {
	if u != nil {
		lec.SetOrderID(*u)
	}
	return lec
}

// SetAssignmentID sets the "assignment_id" field.
func (lec *LogisticsEventCreate) SetAssignmentID(u uuid.UUID) *LogisticsEventCreate {
	lec.mutation.SetAssignmentID(u)
	return lec
}

// SetNillableAssignmentID sets the "assignment_id" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableAssignmentID(u *uuid.UUID) *LogisticsEventCreate {
	if u != nil {
		lec.SetAssignmentID(*u)
	}
	return lec
}

// SetLogisticsTaskID sets the "logistics_task_id" field.
func (lec *LogisticsEventCreate) SetLogisticsTaskID(s string) *LogisticsEventCreate {
	lec.mutation.SetLogisticsTaskID(s)
	return lec
}

// SetNillableLogisticsTaskID sets the "logistics_task_id" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableLogisticsTaskID(s *string) *LogisticsEventCreate {
	if s != nil {
		lec.SetLogisticsTaskID(*s)
	}
	return lec
}

// SetRiderID sets the "rider_id" field.
func (lec *LogisticsEventCreate) SetRiderID(s string) *LogisticsEventCreate {
	lec.mutation.SetRiderID(s)
	return lec
}

// SetNillableRiderID sets the "rider_id" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableRiderID(s *string) *LogisticsEventCreate {
	if s != nil {
		lec.SetRiderID(*s)
	}
	return lec
}

// SetPayload sets the "payload" field.
func (lec *LogisticsEventCreate) SetPayload(m map[string]interface{}) *LogisticsEventCreate {
	lec.mutation.SetPayload(m)
	return lec
}

// SetHeaders sets the "headers" field.
func (lec *LogisticsEventCreate) SetHeaders(m map[string]string) *LogisticsEventCreate {
	lec.mutation.SetHeaders(m)
	return lec
}

// SetSignature sets the "signature" field.
func (lec *LogisticsEventCreate) SetSignature(s string) *LogisticsEventCreate {
	lec.mutation.SetSignature(s)
	return lec
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableSignature(s *string) *LogisticsEventCreate {
	if s != nil {
		lec.SetSignature(*s)
	}
	return lec
}

// SetSignatureValid sets the "signature_valid" field.
func (lec *LogisticsEventCreate) SetSignatureValid(b bool) *LogisticsEventCreate {
	lec.mutation.SetSignatureValid(b)
	return lec
}

// SetNillableSignatureValid sets the "signature_valid" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableSignatureValid(b *bool) *LogisticsEventCreate {
	if b != nil {
		lec.SetSignatureValid(*b)
	}
	return lec
}

// SetStatus sets the "status" field.
func (lec *LogisticsEventCreate) SetStatus(l logisticsevent.Status) *LogisticsEventCreate {
	lec.mutation.SetStatus(l)
	return lec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableStatus(l *logisticsevent.Status) *LogisticsEventCreate {
	if l != nil {
		lec.SetStatus(*l)
	}
	return lec
}

// SetRetryCount sets the "retry_count" field.
func (lec *LogisticsEventCreate) SetRetryCount(i int) *LogisticsEventCreate {
	lec.mutation.SetRetryCount(i)
	return lec
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableRetryCount(i *int) *LogisticsEventCreate {
	if i != nil {
		lec.SetRetryCount(*i)
	}
	return lec
}

// SetLastRetryAt sets the "last_retry_at" field.
func (lec *LogisticsEventCreate) SetLastRetryAt(t time.Time) *LogisticsEventCreate {
	lec.mutation.SetLastRetryAt(t)
	return lec
}

// SetNillableLastRetryAt sets the "last_retry_at" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableLastRetryAt(t *time.Time) *LogisticsEventCreate {
	if t != nil {
		lec.SetLastRetryAt(*t)
	}
	return lec
}

// SetErrorMessage sets the "error_message" field.
func (lec *LogisticsEventCreate) SetErrorMessage(s string) *LogisticsEventCreate {
	lec.mutation.SetErrorMessage(s)
	return lec
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableErrorMessage(s *string) *LogisticsEventCreate {
	if s != nil {
		lec.SetErrorMessage(*s)
	}
	return lec
}

// SetErrorCode sets the "error_code" field.
func (lec *LogisticsEventCreate) SetErrorCode(s string) *LogisticsEventCreate {
	lec.mutation.SetErrorCode(s)
	return lec
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableErrorCode(s *string) *LogisticsEventCreate {
	if s != nil {
		lec.SetErrorCode(*s)
	}
	return lec
}

// SetIPAddress sets the "ip_address" field.
func (lec *LogisticsEventCreate) SetIPAddress(s string) *LogisticsEventCreate {
	lec.mutation.SetIPAddress(s)
	return lec
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableIPAddress(s *string) *LogisticsEventCreate {
	if s != nil {
		lec.SetIPAddress(*s)
	}
	return lec
}

// SetReceivedAt sets the "received_at" field.
func (lec *LogisticsEventCreate) SetReceivedAt(t time.Time) *LogisticsEventCreate {
	lec.mutation.SetReceivedAt(t)
	return lec
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableReceivedAt(t *time.Time) *LogisticsEventCreate {
	if t != nil {
		lec.SetReceivedAt(*t)
	}
	return lec
}

// SetProcessedAt sets the "processed_at" field.
func (lec *LogisticsEventCreate) SetProcessedAt(t time.Time) *LogisticsEventCreate {
	lec.mutation.SetProcessedAt(t)
	return lec
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableProcessedAt(t *time.Time) *LogisticsEventCreate {
	if t != nil {
		lec.SetProcessedAt(*t)
	}
	return lec
}

// SetCreatedAt sets the "created_at" field.
func (lec *LogisticsEventCreate) SetCreatedAt(t time.Time) *LogisticsEventCreate {
	lec.mutation.SetCreatedAt(t)
	return lec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableCreatedAt(t *time.Time) *LogisticsEventCreate {
	if t != nil {
		lec.SetCreatedAt(*t)
	}
	return lec
}

// SetUpdatedAt sets the "updated_at" field.
func (lec *LogisticsEventCreate) SetUpdatedAt(t time.Time) *LogisticsEventCreate {
	lec.mutation.SetUpdatedAt(t)
	return lec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableUpdatedAt(t *time.Time) *LogisticsEventCreate {
	if t != nil {
		lec.SetUpdatedAt(*t)
	}
	return lec
}

// SetID sets the "id" field.
func (lec *LogisticsEventCreate) SetID(u uuid.UUID) *LogisticsEventCreate {
	lec.mutation.SetID(u)
	return lec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (lec *LogisticsEventCreate) SetNillableID(u *uuid.UUID) *LogisticsEventCreate {
	if u != nil {
		lec.SetID(*u)
	}
	return lec
}

// Mutation returns the LogisticsEventMutation object of the builder.
func (lec *LogisticsEventCreate) Mutation() *LogisticsEventMutation {
	return lec.mutation
}

// Save creates the LogisticsEvent in the database.
func (lec *LogisticsEventCreate) Save(ctx context.Context) (*LogisticsEvent, error) {
	lec.defaults()
	return withHooks(ctx, lec.sqlSave, lec.mutation, lec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lec *LogisticsEventCreate) SaveX(ctx context.Context) *LogisticsEvent {
	v, err := lec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lec *LogisticsEventCreate) Exec(ctx context.Context) error {
	_, err := lec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lec *LogisticsEventCreate) ExecX(ctx context.Context) {
	if err := lec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lec *LogisticsEventCreate) defaults() {
	if _, ok := lec.mutation.Status(); !ok {
		v := logisticsevent.DefaultStatus
		lec.mutation.SetStatus(v)
	}
	if _, ok := lec.mutation.RetryCount(); !ok {
		v := logisticsevent.DefaultRetryCount
		lec.mutation.SetRetryCount(v)
	}
	if _, ok := lec.mutation.ReceivedAt(); !ok {
		v := logisticsevent.DefaultReceivedAt()
		lec.mutation.SetReceivedAt(v)
	}
	if _, ok := lec.mutation.CreatedAt(); !ok {
		v := logisticsevent.DefaultCreatedAt()
		lec.mutation.SetCreatedAt(v)
	}
	if _, ok := lec.mutation.UpdatedAt(); !ok {
		v := logisticsevent.DefaultUpdatedAt()
		lec.mutation.SetUpdatedAt(v)
	}
	if _, ok := lec.mutation.ID(); !ok {
		v := logisticsevent.DefaultID()
		lec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lec *LogisticsEventCreate) check() error {
	if _, ok := lec.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "LogisticsEvent.external_id"`)}
	}
	if v, ok := lec.mutation.ExternalID(); ok {
		if err := logisticsevent.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "LogisticsEvent.external_id": %w`, err)}
		}
	}
	if _, ok := lec.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "LogisticsEvent.event_type"`)}
	}
	if v, ok := lec.mutation.EventType(); ok {
		if err := logisticsevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "LogisticsEvent.event_type": %w`, err)}
		}
	}
	if v, ok := lec.mutation.LogisticsTaskID(); ok {
		if err := logisticsevent.LogisticsTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "logistics_task_id", err: fmt.Errorf(`ent: validator failed for field "LogisticsEvent.logistics_task_id": %w`, err)}
		}
	}
	if v, ok := lec.mutation.RiderID(); ok {
		if err := logisticsevent.RiderIDValidator(v); err != nil {
			return &ValidationError{Name: "rider_id", err: fmt.Errorf(`ent: validator failed for field "LogisticsEvent.rider_id": %w`, err)}
		}
	}
	if _, ok := lec.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "LogisticsEvent.payload"`)}
	}
	if v, ok := lec.mutation.Signature(); ok {
		if err := logisticsevent.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`ent: validator failed for field "LogisticsEvent.signature": %w`, err)}
		}
	}
	if _, ok := lec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LogisticsEvent.status"`)}
	}
	if v, ok := lec.mutation.Status(); ok {
		if err := logisticsevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LogisticsEvent.status": %w`, err)}
		}
	}
	if _, ok := lec.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "LogisticsEvent.retry_count"`)}
	}
	if v, ok := lec.mutation.ErrorCode(); ok {
		if err := logisticsevent.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "LogisticsEvent.error_code": %w`, err)}
		}
	}
	if v, ok := lec.mutation.IPAddress(); ok {
		if err := logisticsevent.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "LogisticsEvent.ip_address": %w`, err)}
		}
	}
	if _, ok := lec.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "LogisticsEvent.received_at"`)}
	}
	if _, ok := lec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LogisticsEvent.created_at"`)}
	}
	if _, ok := lec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LogisticsEvent.updated_at"`)}
	}
	return nil
}

func (lec *LogisticsEventCreate) sqlSave(ctx context.Context) (*LogisticsEvent, error) {
	if err := lec.check(); err != nil {
		return nil, err
	}
	_node, _spec := lec.createSpec()
	if err := sqlgraph.CreateNode(ctx, lec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	lec.mutation.id = &_node.ID
	lec.mutation.done = true
	return _node, nil
}

func (lec *LogisticsEventCreate) createSpec() (*LogisticsEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &LogisticsEvent{config: lec.config}
		_spec = sqlgraph.NewCreateSpec(logisticsevent.Table, sqlgraph.NewFieldSpec(logisticsevent.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = lec.conflict
	if id, ok := lec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := lec.mutation.TenantID(); ok {
		_spec.SetField(logisticsevent.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = &value
	}
	if value, ok := lec.mutation.ExternalID(); ok {
		_spec.SetField(logisticsevent.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := lec.mutation.EventType(); ok {
		_spec.SetField(logisticsevent.FieldEventType, field.TypeEnum, value)
		_node.EventType = value
	}
	if value, ok := lec.mutation.OrderID(); ok {
		_spec.SetField(logisticsevent.FieldOrderID, field.TypeUUID, value)
		_node.OrderID = &value
	}
	if value, ok := lec.mutation.AssignmentID(); ok {
		_spec.SetField(logisticsevent.FieldAssignmentID, field.TypeUUID, value)
		_node.AssignmentID = &value
	}
	if value, ok := lec.mutation.LogisticsTaskID(); ok {
		_spec.SetField(logisticsevent.FieldLogisticsTaskID, field.TypeString, value)
		_node.LogisticsTaskID = value
	}
	if value, ok := lec.mutation.RiderID(); ok {
		_spec.SetField(logisticsevent.FieldRiderID, field.TypeString, value)
		_node.RiderID = value
	}
	if value, ok := lec.mutation.Payload(); ok {
		_spec.SetField(logisticsevent.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := lec.mutation.Headers(); ok {
		_spec.SetField(logisticsevent.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := lec.mutation.Signature(); ok {
		_spec.SetField(logisticsevent.FieldSignature, field.TypeString, value)
		_node.Signature = value
	}
	if value, ok := lec.mutation.SignatureValid(); ok {
		_spec.SetField(logisticsevent.FieldSignatureValid, field.TypeBool, value)
		_node.SignatureValid = &value
	}
	if value, ok := lec.mutation.Status(); ok {
		_spec.SetField(logisticsevent.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := lec.mutation.RetryCount(); ok {
		_spec.SetField(logisticsevent.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := lec.mutation.LastRetryAt(); ok {
		_spec.SetField(logisticsevent.FieldLastRetryAt, field.TypeTime, value)
		_node.LastRetryAt = &value
	}
	if value, ok := lec.mutation.ErrorMessage(); ok {
		_spec.SetField(logisticsevent.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := lec.mutation.ErrorCode(); ok {
		_spec.SetField(logisticsevent.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := lec.mutation.IPAddress(); ok {
		_spec.SetField(logisticsevent.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := lec.mutation.ReceivedAt(); ok {
		_spec.SetField(logisticsevent.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	if value, ok := lec.mutation.ProcessedAt(); ok {
		_spec.SetField(logisticsevent.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if value, ok := lec.mutation.CreatedAt(); ok {
		_spec.SetField(logisticsevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := lec.mutation.UpdatedAt(); ok {
		_spec.SetField(logisticsevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LogisticsEvent.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LogisticsEventUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (lec *LogisticsEventCreate) OnConflict(opts ...sql.ConflictOption) *LogisticsEventUpsertOne {
	lec.conflict = opts
	return &LogisticsEventUpsertOne{
		create: lec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LogisticsEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (lec *LogisticsEventCreate) OnConflictColumns(columns ...string) *LogisticsEventUpsertOne {
	lec.conflict = append(lec.conflict, sql.ConflictColumns(columns...))
	return &LogisticsEventUpsertOne{
		create: lec,
	}
}

type (
	// LogisticsEventUpsertOne is the builder for "upsert"-ing
	//  one LogisticsEvent node.
	LogisticsEventUpsertOne struct {
		create *LogisticsEventCreate
	}

	// LogisticsEventUpsert is the "OnConflict" setter.
	LogisticsEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *LogisticsEventUpsert) SetTenantID(v uuid.UUID) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateTenantID() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldTenantID)
	return u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *LogisticsEventUpsert) ClearTenantID() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldTenantID)
	return u
}

// SetExternalID sets the "external_id" field.
func (u *LogisticsEventUpsert) SetExternalID(v string) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldExternalID, v)
	return u
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateExternalID() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldExternalID)
	return u
}

// SetEventType sets the "event_type" field.
func (u *LogisticsEventUpsert) SetEventType(v logisticsevent.EventType) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateEventType() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldEventType)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *LogisticsEventUpsert) SetOrderID(v uuid.UUID) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateOrderID() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldOrderID)
	return u
}

// ClearOrderID clears the value of the "order_id" field.
func (u *LogisticsEventUpsert) ClearOrderID() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldOrderID)
	return u
}

// SetAssignmentID sets the "assignment_id" field.
func (u *LogisticsEventUpsert) SetAssignmentID(v uuid.UUID) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldAssignmentID, v)
	return u
}

// UpdateAssignmentID sets the "assignment_id" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateAssignmentID() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldAssignmentID)
	return u
}

// ClearAssignmentID clears the value of the "assignment_id" field.
func (u *LogisticsEventUpsert) ClearAssignmentID() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldAssignmentID)
	return u
}

// SetLogisticsTaskID sets the "logistics_task_id" field.
func (u *LogisticsEventUpsert) SetLogisticsTaskID(v string) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldLogisticsTaskID, v)
	return u
}

// UpdateLogisticsTaskID sets the "logistics_task_id" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateLogisticsTaskID() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldLogisticsTaskID)
	return u
}

// ClearLogisticsTaskID clears the value of the "logistics_task_id" field.
func (u *LogisticsEventUpsert) ClearLogisticsTaskID() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldLogisticsTaskID)
	return u
}

// SetRiderID sets the "rider_id" field.
func (u *LogisticsEventUpsert) SetRiderID(v string) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldRiderID, v)
	return u
}

// UpdateRiderID sets the "rider_id" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateRiderID() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldRiderID)
	return u
}

// ClearRiderID clears the value of the "rider_id" field.
func (u *LogisticsEventUpsert) ClearRiderID() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldRiderID)
	return u
}

// SetPayload sets the "payload" field.
func (u *LogisticsEventUpsert) SetPayload(v map[string]interface{}) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdatePayload() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldPayload)
	return u
}

// SetHeaders sets the "headers" field.
func (u *LogisticsEventUpsert) SetHeaders(v map[string]string) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldHeaders, v)
	return u
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateHeaders() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldHeaders)
	return u
}

// ClearHeaders clears the value of the "headers" field.
func (u *LogisticsEventUpsert) ClearHeaders() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldHeaders)
	return u
}

// SetSignature sets the "signature" field.
func (u *LogisticsEventUpsert) SetSignature(v string) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldSignature, v)
	return u
}

// UpdateSignature sets the "signature" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateSignature() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldSignature)
	return u
}

// ClearSignature clears the value of the "signature" field.
func (u *LogisticsEventUpsert) ClearSignature() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldSignature)
	return u
}

// SetSignatureValid sets the "signature_valid" field.
func (u *LogisticsEventUpsert) SetSignatureValid(v bool) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldSignatureValid, v)
	return u
}

// UpdateSignatureValid sets the "signature_valid" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateSignatureValid() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldSignatureValid)
	return u
}

// ClearSignatureValid clears the value of the "signature_valid" field.
func (u *LogisticsEventUpsert) ClearSignatureValid() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldSignatureValid)
	return u
}

// SetStatus sets the "status" field.
func (u *LogisticsEventUpsert) SetStatus(v logisticsevent.Status) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateStatus() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldStatus)
	return u
}

// SetRetryCount sets the "retry_count" field.
func (u *LogisticsEventUpsert) SetRetryCount(v int) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldRetryCount, v)
	return u
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateRetryCount() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldRetryCount)
	return u
}

// AddRetryCount adds v to the "retry_count" field.
func (u *LogisticsEventUpsert) AddRetryCount(v int) *LogisticsEventUpsert {
	u.Add(logisticsevent.FieldRetryCount, v)
	return u
}

// SetLastRetryAt sets the "last_retry_at" field.
func (u *LogisticsEventUpsert) SetLastRetryAt(v time.Time) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldLastRetryAt, v)
	return u
}

// UpdateLastRetryAt sets the "last_retry_at" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateLastRetryAt() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldLastRetryAt)
	return u
}

// ClearLastRetryAt clears the value of the "last_retry_at" field.
func (u *LogisticsEventUpsert) ClearLastRetryAt() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldLastRetryAt)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *LogisticsEventUpsert) SetErrorMessage(v string) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateErrorMessage() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *LogisticsEventUpsert) ClearErrorMessage() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldErrorMessage)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *LogisticsEventUpsert) SetErrorCode(v string) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateErrorCode() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *LogisticsEventUpsert) ClearErrorCode() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldErrorCode)
	return u
}

// SetIPAddress sets the "ip_address" field.
func (u *LogisticsEventUpsert) SetIPAddress(v string) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldIPAddress, v)
	return u
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateIPAddress() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldIPAddress)
	return u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *LogisticsEventUpsert) ClearIPAddress() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldIPAddress)
	return u
}

// SetReceivedAt sets the "received_at" field.
func (u *LogisticsEventUpsert) SetReceivedAt(v time.Time) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldReceivedAt, v)
	return u
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateReceivedAt() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldReceivedAt)
	return u
}

// SetProcessedAt sets the "processed_at" field.
func (u *LogisticsEventUpsert) SetProcessedAt(v time.Time) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldProcessedAt, v)
	return u
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateProcessedAt() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldProcessedAt)
	return u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *LogisticsEventUpsert) ClearProcessedAt() *LogisticsEventUpsert {
	u.SetNull(logisticsevent.FieldProcessedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LogisticsEventUpsert) SetUpdatedAt(v time.Time) *LogisticsEventUpsert {
	u.Set(logisticsevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LogisticsEventUpsert) UpdateUpdatedAt() *LogisticsEventUpsert {
	u.SetExcluded(logisticsevent.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LogisticsEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(logisticsevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LogisticsEventUpsertOne) UpdateNewValues() *LogisticsEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(logisticsevent.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(logisticsevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LogisticsEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LogisticsEventUpsertOne) Ignore() *LogisticsEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LogisticsEventUpsertOne) DoNothing() *LogisticsEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LogisticsEventCreate.OnConflict
// documentation for more info.
func (u *LogisticsEventUpsertOne) Update(set func(*LogisticsEventUpsert)) *LogisticsEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LogisticsEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *LogisticsEventUpsertOne) SetTenantID(v uuid.UUID) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateTenantID() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *LogisticsEventUpsertOne) ClearTenantID() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearTenantID()
	})
}

// SetExternalID sets the "external_id" field.
func (u *LogisticsEventUpsertOne) SetExternalID(v string) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateExternalID() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateExternalID()
	})
}

// SetEventType sets the "event_type" field.
func (u *LogisticsEventUpsertOne) SetEventType(v logisticsevent.EventType) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateEventType() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateEventType()
	})
}

// SetOrderID sets the "order_id" field.
func (u *LogisticsEventUpsertOne) SetOrderID(v uuid.UUID) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateOrderID() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *LogisticsEventUpsertOne) ClearOrderID() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearOrderID()
	})
}

// SetAssignmentID sets the "assignment_id" field.
func (u *LogisticsEventUpsertOne) SetAssignmentID(v uuid.UUID) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetAssignmentID(v)
	})
}

// UpdateAssignmentID sets the "assignment_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateAssignmentID() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateAssignmentID()
	})
}

// ClearAssignmentID clears the value of the "assignment_id" field.
func (u *LogisticsEventUpsertOne) ClearAssignmentID() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearAssignmentID()
	})
}

// SetLogisticsTaskID sets the "logistics_task_id" field.
func (u *LogisticsEventUpsertOne) SetLogisticsTaskID(v string) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetLogisticsTaskID(v)
	})
}

// UpdateLogisticsTaskID sets the "logistics_task_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateLogisticsTaskID() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateLogisticsTaskID()
	})
}

// ClearLogisticsTaskID clears the value of the "logistics_task_id" field.
func (u *LogisticsEventUpsertOne) ClearLogisticsTaskID() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearLogisticsTaskID()
	})
}

// SetRiderID sets the "rider_id" field.
func (u *LogisticsEventUpsertOne) SetRiderID(v string) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetRiderID(v)
	})
}

// UpdateRiderID sets the "rider_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateRiderID() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateRiderID()
	})
}

// ClearRiderID clears the value of the "rider_id" field.
func (u *LogisticsEventUpsertOne) ClearRiderID() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearRiderID()
	})
}

// SetPayload sets the "payload" field.
func (u *LogisticsEventUpsertOne) SetPayload(v map[string]interface{}) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdatePayload() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdatePayload()
	})
}

// SetHeaders sets the "headers" field.
func (u *LogisticsEventUpsertOne) SetHeaders(v map[string]string) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetHeaders(v)
	})
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateHeaders() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateHeaders()
	})
}

// ClearHeaders clears the value of the "headers" field.
func (u *LogisticsEventUpsertOne) ClearHeaders() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearHeaders()
	})
}

// SetSignature sets the "signature" field.
func (u *LogisticsEventUpsertOne) SetSignature(v string) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetSignature(v)
	})
}

// UpdateSignature sets the "signature" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateSignature() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateSignature()
	})
}

// ClearSignature clears the value of the "signature" field.
func (u *LogisticsEventUpsertOne) ClearSignature() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearSignature()
	})
}

// SetSignatureValid sets the "signature_valid" field.
func (u *LogisticsEventUpsertOne) SetSignatureValid(v bool) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetSignatureValid(v)
	})
}

// UpdateSignatureValid sets the "signature_valid" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateSignatureValid() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateSignatureValid()
	})
}

// ClearSignatureValid clears the value of the "signature_valid" field.
func (u *LogisticsEventUpsertOne) ClearSignatureValid() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearSignatureValid()
	})
}

// SetStatus sets the "status" field.
func (u *LogisticsEventUpsertOne) SetStatus(v logisticsevent.Status) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateStatus() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateStatus()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *LogisticsEventUpsertOne) SetRetryCount(v int) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *LogisticsEventUpsertOne) AddRetryCount(v int) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateRetryCount() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateRetryCount()
	})
}

// SetLastRetryAt sets the "last_retry_at" field.
func (u *LogisticsEventUpsertOne) SetLastRetryAt(v time.Time) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetLastRetryAt(v)
	})
}

// UpdateLastRetryAt sets the "last_retry_at" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateLastRetryAt() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateLastRetryAt()
	})
}

// ClearLastRetryAt clears the value of the "last_retry_at" field.
func (u *LogisticsEventUpsertOne) ClearLastRetryAt() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearLastRetryAt()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *LogisticsEventUpsertOne) SetErrorMessage(v string) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateErrorMessage() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *LogisticsEventUpsertOne) ClearErrorMessage() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearErrorMessage()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *LogisticsEventUpsertOne) SetErrorCode(v string) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateErrorCode() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *LogisticsEventUpsertOne) ClearErrorCode() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearErrorCode()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *LogisticsEventUpsertOne) SetIPAddress(v string) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateIPAddress() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *LogisticsEventUpsertOne) ClearIPAddress() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearIPAddress()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *LogisticsEventUpsertOne) SetReceivedAt(v time.Time) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateReceivedAt() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateReceivedAt()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *LogisticsEventUpsertOne) SetProcessedAt(v time.Time) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateProcessedAt() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *LogisticsEventUpsertOne) ClearProcessedAt() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearProcessedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LogisticsEventUpsertOne) SetUpdatedAt(v time.Time) *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LogisticsEventUpsertOne) UpdateUpdatedAt() *LogisticsEventUpsertOne {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LogisticsEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LogisticsEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LogisticsEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LogisticsEventUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: LogisticsEventUpsertOne.ID is not supported by MySQL driver. Use LogisticsEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LogisticsEventUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LogisticsEventCreateBulk is the builder for creating many LogisticsEvent entities in bulk.
type LogisticsEventCreateBulk struct {
	config
	err      error
	builders []*LogisticsEventCreate
	conflict []sql.ConflictOption
}

// Save creates the LogisticsEvent entities in the database.
func (lecb *LogisticsEventCreateBulk) Save(ctx context.Context) ([]*LogisticsEvent, error) {
	if lecb.err != nil {
		return nil, lecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lecb.builders))
	nodes := make([]*LogisticsEvent, len(lecb.builders))
	mutators := make([]Mutator, len(lecb.builders))
	for i := range lecb.builders {
		func(i int, root context.Context) {
			builder := lecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LogisticsEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = lecb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lecb *LogisticsEventCreateBulk) SaveX(ctx context.Context) []*LogisticsEvent {
	v, err := lecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lecb *LogisticsEventCreateBulk) Exec(ctx context.Context) error {
	_, err := lecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lecb *LogisticsEventCreateBulk) ExecX(ctx context.Context) {
	if err := lecb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LogisticsEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LogisticsEventUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (lecb *LogisticsEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *LogisticsEventUpsertBulk {
	lecb.conflict = opts
	return &LogisticsEventUpsertBulk{
		create: lecb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LogisticsEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (lecb *LogisticsEventCreateBulk) OnConflictColumns(columns ...string) *LogisticsEventUpsertBulk {
	lecb.conflict = append(lecb.conflict, sql.ConflictColumns(columns...))
	return &LogisticsEventUpsertBulk{
		create: lecb,
	}
}

// LogisticsEventUpsertBulk is the builder for "upsert"-ing
// a bulk of LogisticsEvent nodes.
type LogisticsEventUpsertBulk struct {
	create *LogisticsEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LogisticsEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(logisticsevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LogisticsEventUpsertBulk) UpdateNewValues() *LogisticsEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(logisticsevent.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(logisticsevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LogisticsEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LogisticsEventUpsertBulk) Ignore() *LogisticsEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LogisticsEventUpsertBulk) DoNothing() *LogisticsEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LogisticsEventCreateBulk.OnConflict
// documentation for more info.
func (u *LogisticsEventUpsertBulk) Update(set func(*LogisticsEventUpsert)) *LogisticsEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LogisticsEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *LogisticsEventUpsertBulk) SetTenantID(v uuid.UUID) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateTenantID() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *LogisticsEventUpsertBulk) ClearTenantID() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearTenantID()
	})
}

// SetExternalID sets the "external_id" field.
func (u *LogisticsEventUpsertBulk) SetExternalID(v string) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateExternalID() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateExternalID()
	})
}

// SetEventType sets the "event_type" field.
func (u *LogisticsEventUpsertBulk) SetEventType(v logisticsevent.EventType) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateEventType() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateEventType()
	})
}

// SetOrderID sets the "order_id" field.
func (u *LogisticsEventUpsertBulk) SetOrderID(v uuid.UUID) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateOrderID() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *LogisticsEventUpsertBulk) ClearOrderID() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearOrderID()
	})
}

// SetAssignmentID sets the "assignment_id" field.
func (u *LogisticsEventUpsertBulk) SetAssignmentID(v uuid.UUID) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetAssignmentID(v)
	})
}

// UpdateAssignmentID sets the "assignment_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateAssignmentID() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateAssignmentID()
	})
}

// ClearAssignmentID clears the value of the "assignment_id" field.
func (u *LogisticsEventUpsertBulk) ClearAssignmentID() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearAssignmentID()
	})
}

// SetLogisticsTaskID sets the "logistics_task_id" field.
func (u *LogisticsEventUpsertBulk) SetLogisticsTaskID(v string) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetLogisticsTaskID(v)
	})
}

// UpdateLogisticsTaskID sets the "logistics_task_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateLogisticsTaskID() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateLogisticsTaskID()
	})
}

// ClearLogisticsTaskID clears the value of the "logistics_task_id" field.
func (u *LogisticsEventUpsertBulk) ClearLogisticsTaskID() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearLogisticsTaskID()
	})
}

// SetRiderID sets the "rider_id" field.
func (u *LogisticsEventUpsertBulk) SetRiderID(v string) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetRiderID(v)
	})
}

// UpdateRiderID sets the "rider_id" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateRiderID() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateRiderID()
	})
}

// ClearRiderID clears the value of the "rider_id" field.
func (u *LogisticsEventUpsertBulk) ClearRiderID() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearRiderID()
	})
}

// SetPayload sets the "payload" field.
func (u *LogisticsEventUpsertBulk) SetPayload(v map[string]interface{}) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdatePayload() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdatePayload()
	})
}

// SetHeaders sets the "headers" field.
func (u *LogisticsEventUpsertBulk) SetHeaders(v map[string]string) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetHeaders(v)
	})
}

// UpdateHeaders sets the "headers" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateHeaders() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateHeaders()
	})
}

// ClearHeaders clears the value of the "headers" field.
func (u *LogisticsEventUpsertBulk) ClearHeaders() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearHeaders()
	})
}

// SetSignature sets the "signature" field.
func (u *LogisticsEventUpsertBulk) SetSignature(v string) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetSignature(v)
	})
}

// UpdateSignature sets the "signature" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateSignature() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateSignature()
	})
}

// ClearSignature clears the value of the "signature" field.
func (u *LogisticsEventUpsertBulk) ClearSignature() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearSignature()
	})
}

// SetSignatureValid sets the "signature_valid" field.
func (u *LogisticsEventUpsertBulk) SetSignatureValid(v bool) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetSignatureValid(v)
	})
}

// UpdateSignatureValid sets the "signature_valid" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateSignatureValid() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateSignatureValid()
	})
}

// ClearSignatureValid clears the value of the "signature_valid" field.
func (u *LogisticsEventUpsertBulk) ClearSignatureValid() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearSignatureValid()
	})
}

// SetStatus sets the "status" field.
func (u *LogisticsEventUpsertBulk) SetStatus(v logisticsevent.Status) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateStatus() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateStatus()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *LogisticsEventUpsertBulk) SetRetryCount(v int) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *LogisticsEventUpsertBulk) AddRetryCount(v int) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateRetryCount() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateRetryCount()
	})
}

// SetLastRetryAt sets the "last_retry_at" field.
func (u *LogisticsEventUpsertBulk) SetLastRetryAt(v time.Time) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetLastRetryAt(v)
	})
}

// UpdateLastRetryAt sets the "last_retry_at" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateLastRetryAt() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateLastRetryAt()
	})
}

// ClearLastRetryAt clears the value of the "last_retry_at" field.
func (u *LogisticsEventUpsertBulk) ClearLastRetryAt() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearLastRetryAt()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *LogisticsEventUpsertBulk) SetErrorMessage(v string) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateErrorMessage() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *LogisticsEventUpsertBulk) ClearErrorMessage() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearErrorMessage()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *LogisticsEventUpsertBulk) SetErrorCode(v string) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateErrorCode() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *LogisticsEventUpsertBulk) ClearErrorCode() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearErrorCode()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *LogisticsEventUpsertBulk) SetIPAddress(v string) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateIPAddress() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *LogisticsEventUpsertBulk) ClearIPAddress() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearIPAddress()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *LogisticsEventUpsertBulk) SetReceivedAt(v time.Time) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateReceivedAt() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateReceivedAt()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *LogisticsEventUpsertBulk) SetProcessedAt(v time.Time) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateProcessedAt() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *LogisticsEventUpsertBulk) ClearProcessedAt() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.ClearProcessedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LogisticsEventUpsertBulk) SetUpdatedAt(v time.Time) *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LogisticsEventUpsertBulk) UpdateUpdatedAt() *LogisticsEventUpsertBulk {
	return u.Update(func(s *LogisticsEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LogisticsEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LogisticsEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LogisticsEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LogisticsEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
