// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/ordering-backend/internal/ent/menuitemschedule"
	"github.com/bengobox/ordering-backend/internal/ent/predicate"
)

// MenuItemScheduleDelete is the builder for deleting a MenuItemSchedule entity.
type MenuItemScheduleDelete struct {
	config
	hooks    []Hook
	mutation *MenuItemScheduleMutation
}

// Where appends a list predicates to the MenuItemScheduleDelete builder.
func (misd *MenuItemScheduleDelete) Where(ps ...predicate.MenuItemSchedule) *MenuItemScheduleDelete {
	misd.mutation.Where(ps...)
	return misd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (misd *MenuItemScheduleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, misd.sqlExec, misd.mutation, misd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (misd *MenuItemScheduleDelete) ExecX(ctx context.Context) int {
	n, err := misd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (misd *MenuItemScheduleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(menuitemschedule.Table, sqlgraph.NewFieldSpec(menuitemschedule.FieldID, field.TypeUUID))
	if ps := misd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, misd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	misd.mutation.done = true
	return affected, err
}

// MenuItemScheduleDeleteOne is the builder for deleting a single MenuItemSchedule entity.
type MenuItemScheduleDeleteOne struct {
	misd *MenuItemScheduleDelete
}

// Where appends a list predicates to the MenuItemScheduleDelete builder.
func (misdo *MenuItemScheduleDeleteOne) Where(ps ...predicate.MenuItemSchedule) *MenuItemScheduleDeleteOne {
	misdo.misd.mutation.Where(ps...)
	return misdo
}

// Exec executes the deletion query.
func (misdo *MenuItemScheduleDeleteOne) Exec(ctx context.Context) error {
	n, err := misdo.misd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{menuitemschedule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (misdo *MenuItemScheduleDeleteOne) ExecX(ctx context.Context) {
	if err := misdo.Exec(ctx); err != nil {
		panic(err)
	}
}
