// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/ordering-backend/internal/ent/notificationsubscription"
	"github.com/google/uuid"
)

// NotificationSubscriptionCreate is the builder for creating a NotificationSubscription entity.
type NotificationSubscriptionCreate struct {
	config
	mutation *NotificationSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (nsc *NotificationSubscriptionCreate) SetTenantID(u uuid.UUID) *NotificationSubscriptionCreate {
	nsc.mutation.SetTenantID(u)
	return nsc
}

// SetUserID sets the "user_id" field.
func (nsc *NotificationSubscriptionCreate) SetUserID(u uuid.UUID) *NotificationSubscriptionCreate {
	nsc.mutation.SetUserID(u)
	return nsc
}

// SetChannel sets the "channel" field.
func (nsc *NotificationSubscriptionCreate) SetChannel(n notificationsubscription.Channel) *NotificationSubscriptionCreate {
	nsc.mutation.SetChannel(n)
	return nsc
}

// SetEventKey sets the "event_key" field.
func (nsc *NotificationSubscriptionCreate) SetEventKey(s string) *NotificationSubscriptionCreate {
	nsc.mutation.SetEventKey(s)
	return nsc
}

// SetIsSubscribed sets the "is_subscribed" field.
func (nsc *NotificationSubscriptionCreate) SetIsSubscribed(b bool) *NotificationSubscriptionCreate {
	nsc.mutation.SetIsSubscribed(b)
	return nsc
}

// SetNillableIsSubscribed sets the "is_subscribed" field if the given value is not nil.
func (nsc *NotificationSubscriptionCreate) SetNillableIsSubscribed(b *bool) *NotificationSubscriptionCreate {
	if b != nil {
		nsc.SetIsSubscribed(*b)
	}
	return nsc
}

// SetUpdatedAt sets the "updated_at" field.
func (nsc *NotificationSubscriptionCreate) SetUpdatedAt(t time.Time) *NotificationSubscriptionCreate {
	nsc.mutation.SetUpdatedAt(t)
	return nsc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (nsc *NotificationSubscriptionCreate) SetNillableUpdatedAt(t *time.Time) *NotificationSubscriptionCreate {
	if t != nil {
		nsc.SetUpdatedAt(*t)
	}
	return nsc
}

// SetID sets the "id" field.
func (nsc *NotificationSubscriptionCreate) SetID(u uuid.UUID) *NotificationSubscriptionCreate {
	nsc.mutation.SetID(u)
	return nsc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (nsc *NotificationSubscriptionCreate) SetNillableID(u *uuid.UUID) *NotificationSubscriptionCreate {
	if u != nil {
		nsc.SetID(*u)
	}
	return nsc
}

// Mutation returns the NotificationSubscriptionMutation object of the builder.
func (nsc *NotificationSubscriptionCreate) Mutation() *NotificationSubscriptionMutation {
	return nsc.mutation
}

// Save creates the NotificationSubscription in the database.
func (nsc *NotificationSubscriptionCreate) Save(ctx context.Context) (*NotificationSubscription, error) {
	nsc.defaults()
	return withHooks(ctx, nsc.sqlSave, nsc.mutation, nsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nsc *NotificationSubscriptionCreate) SaveX(ctx context.Context) *NotificationSubscription {
	v, err := nsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nsc *NotificationSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := nsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nsc *NotificationSubscriptionCreate) ExecX(ctx context.Context) {
	if err := nsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nsc *NotificationSubscriptionCreate) defaults() {
	if _, ok := nsc.mutation.IsSubscribed(); !ok {
		v := notificationsubscription.DefaultIsSubscribed
		nsc.mutation.SetIsSubscribed(v)
	}
	if _, ok := nsc.mutation.UpdatedAt(); !ok {
		v := notificationsubscription.DefaultUpdatedAt()
		nsc.mutation.SetUpdatedAt(v)
	}
	if _, ok := nsc.mutation.ID(); !ok {
		v := notificationsubscription.DefaultID()
		nsc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nsc *NotificationSubscriptionCreate) check() error {
	if _, ok := nsc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "NotificationSubscription.tenant_id"`)}
	}
	if _, ok := nsc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "NotificationSubscription.user_id"`)}
	}
	if _, ok := nsc.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "NotificationSubscription.channel"`)}
	}
	if v, ok := nsc.mutation.Channel(); ok {
		if err := notificationsubscription.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "NotificationSubscription.channel": %w`, err)}
		}
	}
	if _, ok := nsc.mutation.EventKey(); !ok {
		return &ValidationError{Name: "event_key", err: errors.New(`ent: missing required field "NotificationSubscription.event_key"`)}
	}
	if v, ok := nsc.mutation.EventKey(); ok {
		if err := notificationsubscription.EventKeyValidator(v); err != nil {
			return &ValidationError{Name: "event_key", err: fmt.Errorf(`ent: validator failed for field "NotificationSubscription.event_key": %w`, err)}
		}
	}
	if _, ok := nsc.mutation.IsSubscribed(); !ok {
		return &ValidationError{Name: "is_subscribed", err: errors.New(`ent: missing required field "NotificationSubscription.is_subscribed"`)}
	}
	if _, ok := nsc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationSubscription.updated_at"`)}
	}
	return nil
}

func (nsc *NotificationSubscriptionCreate) sqlSave(ctx context.Context) (*NotificationSubscription, error) {
	if err := nsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	nsc.mutation.id = &_node.ID
	nsc.mutation.done = true
	return _node, nil
}

func (nsc *NotificationSubscriptionCreate) createSpec() (*NotificationSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationSubscription{config: nsc.config}
		_spec = sqlgraph.NewCreateSpec(notificationsubscription.Table, sqlgraph.NewFieldSpec(notificationsubscription.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = nsc.conflict
	if id, ok := nsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := nsc.mutation.TenantID(); ok {
		_spec.SetField(notificationsubscription.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := nsc.mutation.UserID(); ok {
		_spec.SetField(notificationsubscription.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := nsc.mutation.Channel(); ok {
		_spec.SetField(notificationsubscription.FieldChannel, field.TypeEnum, value)
		_node.Channel = value
	}
	if value, ok := nsc.mutation.EventKey(); ok {
		_spec.SetField(notificationsubscription.FieldEventKey, field.TypeString, value)
		_node.EventKey = value
	}
	if value, ok := nsc.mutation.IsSubscribed(); ok {
		_spec.SetField(notificationsubscription.FieldIsSubscribed, field.TypeBool, value)
		_node.IsSubscribed = value
	}
	if value, ok := nsc.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationsubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationSubscription.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationSubscriptionUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (nsc *NotificationSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *NotificationSubscriptionUpsertOne {
	nsc.conflict = opts
	return &NotificationSubscriptionUpsertOne{
		create: nsc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (nsc *NotificationSubscriptionCreate) OnConflictColumns(columns ...string) *NotificationSubscriptionUpsertOne {
	nsc.conflict = append(nsc.conflict, sql.ConflictColumns(columns...))
	return &NotificationSubscriptionUpsertOne{
		create: nsc,
	}
}

type (
	// NotificationSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one NotificationSubscription node.
	NotificationSubscriptionUpsertOne struct {
		create *NotificationSubscriptionCreate
	}

	// NotificationSubscriptionUpsert is the "OnConflict" setter.
	NotificationSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *NotificationSubscriptionUpsert) SetTenantID(v uuid.UUID) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateTenantID() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldTenantID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *NotificationSubscriptionUpsert) SetUserID(v uuid.UUID) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateUserID() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldUserID)
	return u
}

// SetChannel sets the "channel" field.
func (u *NotificationSubscriptionUpsert) SetChannel(v notificationsubscription.Channel) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldChannel, v)
	return u
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateChannel() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldChannel)
	return u
}

// SetEventKey sets the "event_key" field.
func (u *NotificationSubscriptionUpsert) SetEventKey(v string) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldEventKey, v)
	return u
}

// UpdateEventKey sets the "event_key" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateEventKey() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldEventKey)
	return u
}

// SetIsSubscribed sets the "is_subscribed" field.
func (u *NotificationSubscriptionUpsert) SetIsSubscribed(v bool) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldIsSubscribed, v)
	return u
}

// UpdateIsSubscribed sets the "is_subscribed" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateIsSubscribed() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldIsSubscribed)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationSubscriptionUpsert) SetUpdatedAt(v time.Time) *NotificationSubscriptionUpsert {
	u.Set(notificationsubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsert) UpdateUpdatedAt() *NotificationSubscriptionUpsert {
	u.SetExcluded(notificationsubscription.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationsubscription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationSubscriptionUpsertOne) UpdateNewValues() *NotificationSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(notificationsubscription.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationSubscriptionUpsertOne) Ignore() *NotificationSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationSubscriptionUpsertOne) DoNothing() *NotificationSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationSubscriptionCreate.OnConflict
// documentation for more info.
func (u *NotificationSubscriptionUpsertOne) Update(set func(*NotificationSubscriptionUpsert)) *NotificationSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *NotificationSubscriptionUpsertOne) SetTenantID(v uuid.UUID) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateTenantID() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateTenantID()
	})
}

// SetUserID sets the "user_id" field.
func (u *NotificationSubscriptionUpsertOne) SetUserID(v uuid.UUID) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateUserID() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetChannel sets the "channel" field.
func (u *NotificationSubscriptionUpsertOne) SetChannel(v notificationsubscription.Channel) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateChannel() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateChannel()
	})
}

// SetEventKey sets the "event_key" field.
func (u *NotificationSubscriptionUpsertOne) SetEventKey(v string) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetEventKey(v)
	})
}

// UpdateEventKey sets the "event_key" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateEventKey() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateEventKey()
	})
}

// SetIsSubscribed sets the "is_subscribed" field.
func (u *NotificationSubscriptionUpsertOne) SetIsSubscribed(v bool) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetIsSubscribed(v)
	})
}

// UpdateIsSubscribed sets the "is_subscribed" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateIsSubscribed() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateIsSubscribed()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationSubscriptionUpsertOne) SetUpdatedAt(v time.Time) *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertOne) UpdateUpdatedAt() *NotificationSubscriptionUpsertOne {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NotificationSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationSubscriptionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NotificationSubscriptionUpsertOne.ID is not supported by MySQL driver. Use NotificationSubscriptionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationSubscriptionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationSubscriptionCreateBulk is the builder for creating many NotificationSubscription entities in bulk.
type NotificationSubscriptionCreateBulk struct {
	config
	err      error
	builders []*NotificationSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the NotificationSubscription entities in the database.
func (nscb *NotificationSubscriptionCreateBulk) Save(ctx context.Context) ([]*NotificationSubscription, error) {
	if nscb.err != nil {
		return nil, nscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(nscb.builders))
	nodes := make([]*NotificationSubscription, len(nscb.builders))
	mutators := make([]Mutator, len(nscb.builders))
	for i := range nscb.builders {
		func(i int, root context.Context) {
			builder := nscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, nscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = nscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, nscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, nscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (nscb *NotificationSubscriptionCreateBulk) SaveX(ctx context.Context) []*NotificationSubscription {
	v, err := nscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nscb *NotificationSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := nscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nscb *NotificationSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := nscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationSubscriptionUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (nscb *NotificationSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationSubscriptionUpsertBulk {
	nscb.conflict = opts
	return &NotificationSubscriptionUpsertBulk{
		create: nscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (nscb *NotificationSubscriptionCreateBulk) OnConflictColumns(columns ...string) *NotificationSubscriptionUpsertBulk {
	nscb.conflict = append(nscb.conflict, sql.ConflictColumns(columns...))
	return &NotificationSubscriptionUpsertBulk{
		create: nscb,
	}
}

// NotificationSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of NotificationSubscription nodes.
type NotificationSubscriptionUpsertBulk struct {
	create *NotificationSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationsubscription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationSubscriptionUpsertBulk) UpdateNewValues() *NotificationSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(notificationsubscription.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationSubscriptionUpsertBulk) Ignore() *NotificationSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationSubscriptionUpsertBulk) DoNothing() *NotificationSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationSubscriptionUpsertBulk) Update(set func(*NotificationSubscriptionUpsert)) *NotificationSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *NotificationSubscriptionUpsertBulk) SetTenantID(v uuid.UUID) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateTenantID() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateTenantID()
	})
}

// SetUserID sets the "user_id" field.
func (u *NotificationSubscriptionUpsertBulk) SetUserID(v uuid.UUID) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateUserID() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetChannel sets the "channel" field.
func (u *NotificationSubscriptionUpsertBulk) SetChannel(v notificationsubscription.Channel) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateChannel() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateChannel()
	})
}

// SetEventKey sets the "event_key" field.
func (u *NotificationSubscriptionUpsertBulk) SetEventKey(v string) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetEventKey(v)
	})
}

// UpdateEventKey sets the "event_key" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateEventKey() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateEventKey()
	})
}

// SetIsSubscribed sets the "is_subscribed" field.
func (u *NotificationSubscriptionUpsertBulk) SetIsSubscribed(v bool) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetIsSubscribed(v)
	})
}

// UpdateIsSubscribed sets the "is_subscribed" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateIsSubscribed() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateIsSubscribed()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationSubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationSubscriptionUpsertBulk) UpdateUpdatedAt() *NotificationSubscriptionUpsertBulk {
	return u.Update(func(s *NotificationSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NotificationSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
