// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/ordering-backend/internal/ent/notificationsubscription"
	"github.com/google/uuid"
)

// NotificationSubscription is the model entity for the NotificationSubscription schema.
type NotificationSubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Reference to tenant
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Reference to user
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Notification channel
	Channel notificationsubscription.Channel `json:"channel,omitempty"`
	// Event key to subscribe/unsubscribe from
	EventKey string `json:"event_key,omitempty"`
	// Whether user is subscribed to this notification
	IsSubscribed bool `json:"is_subscribed,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationSubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationsubscription.FieldIsSubscribed:
			values[i] = new(sql.NullBool)
		case notificationsubscription.FieldChannel, notificationsubscription.FieldEventKey:
			values[i] = new(sql.NullString)
		case notificationsubscription.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case notificationsubscription.FieldID, notificationsubscription.FieldTenantID, notificationsubscription.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationSubscription fields.
func (ns *NotificationSubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationsubscription.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ns.ID = *value
			}
		case notificationsubscription.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				ns.TenantID = *value
			}
		case notificationsubscription.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				ns.UserID = *value
			}
		case notificationsubscription.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				ns.Channel = notificationsubscription.Channel(value.String)
			}
		case notificationsubscription.FieldEventKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_key", values[i])
			} else if value.Valid {
				ns.EventKey = value.String
			}
		case notificationsubscription.FieldIsSubscribed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_subscribed", values[i])
			} else if value.Valid {
				ns.IsSubscribed = value.Bool
			}
		case notificationsubscription.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ns.UpdatedAt = value.Time
			}
		default:
			ns.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationSubscription.
// This includes values selected through modifiers, order, etc.
func (ns *NotificationSubscription) Value(name string) (ent.Value, error) {
	return ns.selectValues.Get(name)
}

// Update returns a builder for updating this NotificationSubscription.
// Note that you need to call NotificationSubscription.Unwrap() before calling this method if this NotificationSubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (ns *NotificationSubscription) Update() *NotificationSubscriptionUpdateOne {
	return NewNotificationSubscriptionClient(ns.config).UpdateOne(ns)
}

// Unwrap unwraps the NotificationSubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ns *NotificationSubscription) Unwrap() *NotificationSubscription {
	_tx, ok := ns.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationSubscription is not a transactional entity")
	}
	ns.config.driver = _tx.drv
	return ns
}

// String implements the fmt.Stringer.
func (ns *NotificationSubscription) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationSubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ns.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", ns.TenantID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ns.UserID))
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(fmt.Sprintf("%v", ns.Channel))
	builder.WriteString(", ")
	builder.WriteString("event_key=")
	builder.WriteString(ns.EventKey)
	builder.WriteString(", ")
	builder.WriteString("is_subscribed=")
	builder.WriteString(fmt.Sprintf("%v", ns.IsSubscribed))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ns.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationSubscriptions is a parsable slice of NotificationSubscription.
type NotificationSubscriptions []*NotificationSubscription
