// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/ordering-backend/internal/ent/serviceconfig"
	"github.com/google/uuid"
)

// ServiceConfigCreate is the builder for creating a ServiceConfig entity.
type ServiceConfigCreate struct {
	config
	mutation *ServiceConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (scc *ServiceConfigCreate) SetTenantID(u uuid.UUID) *ServiceConfigCreate {
	scc.mutation.SetTenantID(u)
	return scc
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (scc *ServiceConfigCreate) SetNillableTenantID(u *uuid.UUID) *ServiceConfigCreate {
	if u != nil {
		scc.SetTenantID(*u)
	}
	return scc
}

// SetConfigKey sets the "config_key" field.
func (scc *ServiceConfigCreate) SetConfigKey(s string) *ServiceConfigCreate {
	scc.mutation.SetConfigKey(s)
	return scc
}

// SetConfigValue sets the "config_value" field.
func (scc *ServiceConfigCreate) SetConfigValue(s string) *ServiceConfigCreate {
	scc.mutation.SetConfigValue(s)
	return scc
}

// SetConfigType sets the "config_type" field.
func (scc *ServiceConfigCreate) SetConfigType(s string) *ServiceConfigCreate {
	scc.mutation.SetConfigType(s)
	return scc
}

// SetNillableConfigType sets the "config_type" field if the given value is not nil.
func (scc *ServiceConfigCreate) SetNillableConfigType(s *string) *ServiceConfigCreate {
	if s != nil {
		scc.SetConfigType(*s)
	}
	return scc
}

// SetDescription sets the "description" field.
func (scc *ServiceConfigCreate) SetDescription(s string) *ServiceConfigCreate {
	scc.mutation.SetDescription(s)
	return scc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (scc *ServiceConfigCreate) SetNillableDescription(s *string) *ServiceConfigCreate {
	if s != nil {
		scc.SetDescription(*s)
	}
	return scc
}

// SetIsSecret sets the "is_secret" field.
func (scc *ServiceConfigCreate) SetIsSecret(b bool) *ServiceConfigCreate {
	scc.mutation.SetIsSecret(b)
	return scc
}

// SetNillableIsSecret sets the "is_secret" field if the given value is not nil.
func (scc *ServiceConfigCreate) SetNillableIsSecret(b *bool) *ServiceConfigCreate {
	if b != nil {
		scc.SetIsSecret(*b)
	}
	return scc
}

// SetCreatedAt sets the "created_at" field.
func (scc *ServiceConfigCreate) SetCreatedAt(t time.Time) *ServiceConfigCreate {
	scc.mutation.SetCreatedAt(t)
	return scc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (scc *ServiceConfigCreate) SetNillableCreatedAt(t *time.Time) *ServiceConfigCreate {
	if t != nil {
		scc.SetCreatedAt(*t)
	}
	return scc
}

// SetUpdatedAt sets the "updated_at" field.
func (scc *ServiceConfigCreate) SetUpdatedAt(t time.Time) *ServiceConfigCreate {
	scc.mutation.SetUpdatedAt(t)
	return scc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (scc *ServiceConfigCreate) SetNillableUpdatedAt(t *time.Time) *ServiceConfigCreate {
	if t != nil {
		scc.SetUpdatedAt(*t)
	}
	return scc
}

// SetID sets the "id" field.
func (scc *ServiceConfigCreate) SetID(u uuid.UUID) *ServiceConfigCreate {
	scc.mutation.SetID(u)
	return scc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (scc *ServiceConfigCreate) SetNillableID(u *uuid.UUID) *ServiceConfigCreate {
	if u != nil {
		scc.SetID(*u)
	}
	return scc
}

// Mutation returns the ServiceConfigMutation object of the builder.
func (scc *ServiceConfigCreate) Mutation() *ServiceConfigMutation {
	return scc.mutation
}

// Save creates the ServiceConfig in the database.
func (scc *ServiceConfigCreate) Save(ctx context.Context) (*ServiceConfig, error) {
	scc.defaults()
	return withHooks(ctx, scc.sqlSave, scc.mutation, scc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (scc *ServiceConfigCreate) SaveX(ctx context.Context) *ServiceConfig {
	v, err := scc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scc *ServiceConfigCreate) Exec(ctx context.Context) error {
	_, err := scc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scc *ServiceConfigCreate) ExecX(ctx context.Context) {
	if err := scc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (scc *ServiceConfigCreate) defaults() {
	if _, ok := scc.mutation.ConfigType(); !ok {
		v := serviceconfig.DefaultConfigType
		scc.mutation.SetConfigType(v)
	}
	if _, ok := scc.mutation.IsSecret(); !ok {
		v := serviceconfig.DefaultIsSecret
		scc.mutation.SetIsSecret(v)
	}
	if _, ok := scc.mutation.CreatedAt(); !ok {
		v := serviceconfig.DefaultCreatedAt()
		scc.mutation.SetCreatedAt(v)
	}
	if _, ok := scc.mutation.UpdatedAt(); !ok {
		v := serviceconfig.DefaultUpdatedAt()
		scc.mutation.SetUpdatedAt(v)
	}
	if _, ok := scc.mutation.ID(); !ok {
		v := serviceconfig.DefaultID()
		scc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (scc *ServiceConfigCreate) check() error {
	if _, ok := scc.mutation.ConfigKey(); !ok {
		return &ValidationError{Name: "config_key", err: errors.New(`ent: missing required field "ServiceConfig.config_key"`)}
	}
	if v, ok := scc.mutation.ConfigKey(); ok {
		if err := serviceconfig.ConfigKeyValidator(v); err != nil {
			return &ValidationError{Name: "config_key", err: fmt.Errorf(`ent: validator failed for field "ServiceConfig.config_key": %w`, err)}
		}
	}
	if _, ok := scc.mutation.ConfigValue(); !ok {
		return &ValidationError{Name: "config_value", err: errors.New(`ent: missing required field "ServiceConfig.config_value"`)}
	}
	if v, ok := scc.mutation.ConfigValue(); ok {
		if err := serviceconfig.ConfigValueValidator(v); err != nil {
			return &ValidationError{Name: "config_value", err: fmt.Errorf(`ent: validator failed for field "ServiceConfig.config_value": %w`, err)}
		}
	}
	if _, ok := scc.mutation.ConfigType(); !ok {
		return &ValidationError{Name: "config_type", err: errors.New(`ent: missing required field "ServiceConfig.config_type"`)}
	}
	if _, ok := scc.mutation.IsSecret(); !ok {
		return &ValidationError{Name: "is_secret", err: errors.New(`ent: missing required field "ServiceConfig.is_secret"`)}
	}
	if _, ok := scc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ServiceConfig.created_at"`)}
	}
	if _, ok := scc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ServiceConfig.updated_at"`)}
	}
	return nil
}

func (scc *ServiceConfigCreate) sqlSave(ctx context.Context) (*ServiceConfig, error) {
	if err := scc.check(); err != nil {
		return nil, err
	}
	_node, _spec := scc.createSpec()
	if err := sqlgraph.CreateNode(ctx, scc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	scc.mutation.id = &_node.ID
	scc.mutation.done = true
	return _node, nil
}

func (scc *ServiceConfigCreate) createSpec() (*ServiceConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &ServiceConfig{config: scc.config}
		_spec = sqlgraph.NewCreateSpec(serviceconfig.Table, sqlgraph.NewFieldSpec(serviceconfig.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = scc.conflict
	if id, ok := scc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := scc.mutation.TenantID(); ok {
		_spec.SetField(serviceconfig.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = &value
	}
	if value, ok := scc.mutation.ConfigKey(); ok {
		_spec.SetField(serviceconfig.FieldConfigKey, field.TypeString, value)
		_node.ConfigKey = value
	}
	if value, ok := scc.mutation.ConfigValue(); ok {
		_spec.SetField(serviceconfig.FieldConfigValue, field.TypeString, value)
		_node.ConfigValue = value
	}
	if value, ok := scc.mutation.ConfigType(); ok {
		_spec.SetField(serviceconfig.FieldConfigType, field.TypeString, value)
		_node.ConfigType = value
	}
	if value, ok := scc.mutation.Description(); ok {
		_spec.SetField(serviceconfig.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := scc.mutation.IsSecret(); ok {
		_spec.SetField(serviceconfig.FieldIsSecret, field.TypeBool, value)
		_node.IsSecret = value
	}
	if value, ok := scc.mutation.CreatedAt(); ok {
		_spec.SetField(serviceconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := scc.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ServiceConfig.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ServiceConfigUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (scc *ServiceConfigCreate) OnConflict(opts ...sql.ConflictOption) *ServiceConfigUpsertOne {
	scc.conflict = opts
	return &ServiceConfigUpsertOne{
		create: scc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ServiceConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (scc *ServiceConfigCreate) OnConflictColumns(columns ...string) *ServiceConfigUpsertOne {
	scc.conflict = append(scc.conflict, sql.ConflictColumns(columns...))
	return &ServiceConfigUpsertOne{
		create: scc,
	}
}

type (
	// ServiceConfigUpsertOne is the builder for "upsert"-ing
	//  one ServiceConfig node.
	ServiceConfigUpsertOne struct {
		create *ServiceConfigCreate
	}

	// ServiceConfigUpsert is the "OnConflict" setter.
	ServiceConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *ServiceConfigUpsert) SetTenantID(v uuid.UUID) *ServiceConfigUpsert {
	u.Set(serviceconfig.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *ServiceConfigUpsert) UpdateTenantID() *ServiceConfigUpsert {
	u.SetExcluded(serviceconfig.FieldTenantID)
	return u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *ServiceConfigUpsert) ClearTenantID() *ServiceConfigUpsert {
	u.SetNull(serviceconfig.FieldTenantID)
	return u
}

// SetConfigKey sets the "config_key" field.
func (u *ServiceConfigUpsert) SetConfigKey(v string) *ServiceConfigUpsert {
	u.Set(serviceconfig.FieldConfigKey, v)
	return u
}

// UpdateConfigKey sets the "config_key" field to the value that was provided on create.
func (u *ServiceConfigUpsert) UpdateConfigKey() *ServiceConfigUpsert {
	u.SetExcluded(serviceconfig.FieldConfigKey)
	return u
}

// SetConfigValue sets the "config_value" field.
func (u *ServiceConfigUpsert) SetConfigValue(v string) *ServiceConfigUpsert {
	u.Set(serviceconfig.FieldConfigValue, v)
	return u
}

// UpdateConfigValue sets the "config_value" field to the value that was provided on create.
func (u *ServiceConfigUpsert) UpdateConfigValue() *ServiceConfigUpsert {
	u.SetExcluded(serviceconfig.FieldConfigValue)
	return u
}

// SetConfigType sets the "config_type" field.
func (u *ServiceConfigUpsert) SetConfigType(v string) *ServiceConfigUpsert {
	u.Set(serviceconfig.FieldConfigType, v)
	return u
}

// UpdateConfigType sets the "config_type" field to the value that was provided on create.
func (u *ServiceConfigUpsert) UpdateConfigType() *ServiceConfigUpsert {
	u.SetExcluded(serviceconfig.FieldConfigType)
	return u
}

// SetDescription sets the "description" field.
func (u *ServiceConfigUpsert) SetDescription(v string) *ServiceConfigUpsert {
	u.Set(serviceconfig.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ServiceConfigUpsert) UpdateDescription() *ServiceConfigUpsert {
	u.SetExcluded(serviceconfig.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ServiceConfigUpsert) ClearDescription() *ServiceConfigUpsert {
	u.SetNull(serviceconfig.FieldDescription)
	return u
}

// SetIsSecret sets the "is_secret" field.
func (u *ServiceConfigUpsert) SetIsSecret(v bool) *ServiceConfigUpsert {
	u.Set(serviceconfig.FieldIsSecret, v)
	return u
}

// UpdateIsSecret sets the "is_secret" field to the value that was provided on create.
func (u *ServiceConfigUpsert) UpdateIsSecret() *ServiceConfigUpsert {
	u.SetExcluded(serviceconfig.FieldIsSecret)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ServiceConfigUpsert) SetUpdatedAt(v time.Time) *ServiceConfigUpsert {
	u.Set(serviceconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ServiceConfigUpsert) UpdateUpdatedAt() *ServiceConfigUpsert {
	u.SetExcluded(serviceconfig.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ServiceConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(serviceconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ServiceConfigUpsertOne) UpdateNewValues() *ServiceConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(serviceconfig.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(serviceconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ServiceConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ServiceConfigUpsertOne) Ignore() *ServiceConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ServiceConfigUpsertOne) DoNothing() *ServiceConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ServiceConfigCreate.OnConflict
// documentation for more info.
func (u *ServiceConfigUpsertOne) Update(set func(*ServiceConfigUpsert)) *ServiceConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ServiceConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *ServiceConfigUpsertOne) SetTenantID(v uuid.UUID) *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *ServiceConfigUpsertOne) UpdateTenantID() *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *ServiceConfigUpsertOne) ClearTenantID() *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.ClearTenantID()
	})
}

// SetConfigKey sets the "config_key" field.
func (u *ServiceConfigUpsertOne) SetConfigKey(v string) *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetConfigKey(v)
	})
}

// UpdateConfigKey sets the "config_key" field to the value that was provided on create.
func (u *ServiceConfigUpsertOne) UpdateConfigKey() *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateConfigKey()
	})
}

// SetConfigValue sets the "config_value" field.
func (u *ServiceConfigUpsertOne) SetConfigValue(v string) *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetConfigValue(v)
	})
}

// UpdateConfigValue sets the "config_value" field to the value that was provided on create.
func (u *ServiceConfigUpsertOne) UpdateConfigValue() *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateConfigValue()
	})
}

// SetConfigType sets the "config_type" field.
func (u *ServiceConfigUpsertOne) SetConfigType(v string) *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetConfigType(v)
	})
}

// UpdateConfigType sets the "config_type" field to the value that was provided on create.
func (u *ServiceConfigUpsertOne) UpdateConfigType() *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateConfigType()
	})
}

// SetDescription sets the "description" field.
func (u *ServiceConfigUpsertOne) SetDescription(v string) *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ServiceConfigUpsertOne) UpdateDescription() *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ServiceConfigUpsertOne) ClearDescription() *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.ClearDescription()
	})
}

// SetIsSecret sets the "is_secret" field.
func (u *ServiceConfigUpsertOne) SetIsSecret(v bool) *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetIsSecret(v)
	})
}

// UpdateIsSecret sets the "is_secret" field to the value that was provided on create.
func (u *ServiceConfigUpsertOne) UpdateIsSecret() *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateIsSecret()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ServiceConfigUpsertOne) SetUpdatedAt(v time.Time) *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ServiceConfigUpsertOne) UpdateUpdatedAt() *ServiceConfigUpsertOne {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ServiceConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ServiceConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ServiceConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ServiceConfigUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ServiceConfigUpsertOne.ID is not supported by MySQL driver. Use ServiceConfigUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ServiceConfigUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ServiceConfigCreateBulk is the builder for creating many ServiceConfig entities in bulk.
type ServiceConfigCreateBulk struct {
	config
	err      error
	builders []*ServiceConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the ServiceConfig entities in the database.
func (sccb *ServiceConfigCreateBulk) Save(ctx context.Context) ([]*ServiceConfig, error) {
	if sccb.err != nil {
		return nil, sccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sccb.builders))
	nodes := make([]*ServiceConfig, len(sccb.builders))
	mutators := make([]Mutator, len(sccb.builders))
	for i := range sccb.builders {
		func(i int, root context.Context) {
			builder := sccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = sccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sccb *ServiceConfigCreateBulk) SaveX(ctx context.Context) []*ServiceConfig {
	v, err := sccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sccb *ServiceConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := sccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sccb *ServiceConfigCreateBulk) ExecX(ctx context.Context) {
	if err := sccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ServiceConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ServiceConfigUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (sccb *ServiceConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *ServiceConfigUpsertBulk {
	sccb.conflict = opts
	return &ServiceConfigUpsertBulk{
		create: sccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ServiceConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sccb *ServiceConfigCreateBulk) OnConflictColumns(columns ...string) *ServiceConfigUpsertBulk {
	sccb.conflict = append(sccb.conflict, sql.ConflictColumns(columns...))
	return &ServiceConfigUpsertBulk{
		create: sccb,
	}
}

// ServiceConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of ServiceConfig nodes.
type ServiceConfigUpsertBulk struct {
	create *ServiceConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ServiceConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(serviceconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ServiceConfigUpsertBulk) UpdateNewValues() *ServiceConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(serviceconfig.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(serviceconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ServiceConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ServiceConfigUpsertBulk) Ignore() *ServiceConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ServiceConfigUpsertBulk) DoNothing() *ServiceConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ServiceConfigCreateBulk.OnConflict
// documentation for more info.
func (u *ServiceConfigUpsertBulk) Update(set func(*ServiceConfigUpsert)) *ServiceConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ServiceConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *ServiceConfigUpsertBulk) SetTenantID(v uuid.UUID) *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *ServiceConfigUpsertBulk) UpdateTenantID() *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateTenantID()
	})
}

// ClearTenantID clears the value of the "tenant_id" field.
func (u *ServiceConfigUpsertBulk) ClearTenantID() *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.ClearTenantID()
	})
}

// SetConfigKey sets the "config_key" field.
func (u *ServiceConfigUpsertBulk) SetConfigKey(v string) *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetConfigKey(v)
	})
}

// UpdateConfigKey sets the "config_key" field to the value that was provided on create.
func (u *ServiceConfigUpsertBulk) UpdateConfigKey() *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateConfigKey()
	})
}

// SetConfigValue sets the "config_value" field.
func (u *ServiceConfigUpsertBulk) SetConfigValue(v string) *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetConfigValue(v)
	})
}

// UpdateConfigValue sets the "config_value" field to the value that was provided on create.
func (u *ServiceConfigUpsertBulk) UpdateConfigValue() *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateConfigValue()
	})
}

// SetConfigType sets the "config_type" field.
func (u *ServiceConfigUpsertBulk) SetConfigType(v string) *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetConfigType(v)
	})
}

// UpdateConfigType sets the "config_type" field to the value that was provided on create.
func (u *ServiceConfigUpsertBulk) UpdateConfigType() *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateConfigType()
	})
}

// SetDescription sets the "description" field.
func (u *ServiceConfigUpsertBulk) SetDescription(v string) *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ServiceConfigUpsertBulk) UpdateDescription() *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ServiceConfigUpsertBulk) ClearDescription() *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.ClearDescription()
	})
}

// SetIsSecret sets the "is_secret" field.
func (u *ServiceConfigUpsertBulk) SetIsSecret(v bool) *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetIsSecret(v)
	})
}

// UpdateIsSecret sets the "is_secret" field to the value that was provided on create.
func (u *ServiceConfigUpsertBulk) UpdateIsSecret() *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateIsSecret()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ServiceConfigUpsertBulk) SetUpdatedAt(v time.Time) *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ServiceConfigUpsertBulk) UpdateUpdatedAt() *ServiceConfigUpsertBulk {
	return u.Update(func(s *ServiceConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ServiceConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ServiceConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ServiceConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ServiceConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
