// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/ordering-backend/internal/ent/predicate"
	"github.com/bengobox/ordering-backend/internal/ent/tenant"
	"github.com/bengobox/ordering-backend/internal/ent/tenantsyncevent"
	"github.com/google/uuid"
)

// TenantSyncEventUpdate is the builder for updating TenantSyncEvent entities.
type TenantSyncEventUpdate struct {
	config
	hooks    []Hook
	mutation *TenantSyncEventMutation
}

// Where appends a list predicates to the TenantSyncEventUpdate builder.
func (_u *TenantSyncEventUpdate) Where(ps ...predicate.TenantSyncEvent) *TenantSyncEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantSyncEventUpdate) SetTenantID(v uuid.UUID) *TenantSyncEventUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantSyncEventUpdate) SetNillableTenantID(v *uuid.UUID) *TenantSyncEventUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetDestinationService sets the "destination_service" field.
func (_u *TenantSyncEventUpdate) SetDestinationService(v string) *TenantSyncEventUpdate {
	_u.mutation.SetDestinationService(v)
	return _u
}

// SetNillableDestinationService sets the "destination_service" field if the given value is not nil.
func (_u *TenantSyncEventUpdate) SetNillableDestinationService(v *string) *TenantSyncEventUpdate {
	if v != nil {
		_u.SetDestinationService(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *TenantSyncEventUpdate) SetPayload(v map[string]interface{}) *TenantSyncEventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantSyncEventUpdate) SetStatus(v string) *TenantSyncEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantSyncEventUpdate) SetNillableStatus(v *string) *TenantSyncEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *TenantSyncEventUpdate) SetAttempts(v int) *TenantSyncEventUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *TenantSyncEventUpdate) SetNillableAttempts(v *int) *TenantSyncEventUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *TenantSyncEventUpdate) AddAttempts(v int) *TenantSyncEventUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *TenantSyncEventUpdate) SetSyncedAt(v time.Time) *TenantSyncEventUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *TenantSyncEventUpdate) SetNillableSyncedAt(v *time.Time) *TenantSyncEventUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *TenantSyncEventUpdate) ClearSyncedAt() *TenantSyncEventUpdate {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantSyncEventUpdate) SetUpdatedAt(v time.Time) *TenantSyncEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantSyncEventUpdate) SetTenant(v *Tenant) *TenantSyncEventUpdate {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the TenantSyncEventMutation object of the builder.
func (_u *TenantSyncEventUpdate) Mutation() *TenantSyncEventMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantSyncEventUpdate) ClearTenant() *TenantSyncEventUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantSyncEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantSyncEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantSyncEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantSyncEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantSyncEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantsyncevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantSyncEventUpdate) check() error {
	if v, ok := _u.mutation.DestinationService(); ok {
		if err := tenantsyncevent.DestinationServiceValidator(v); err != nil {
			return &ValidationError{Name: "destination_service", err: fmt.Errorf(`ent: validator failed for field "TenantSyncEvent.destination_service": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantSyncEvent.tenant"`)
	}
	return nil
}

func (_u *TenantSyncEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantsyncevent.Table, tenantsyncevent.Columns, sqlgraph.NewFieldSpec(tenantsyncevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DestinationService(); ok {
		_spec.SetField(tenantsyncevent.FieldDestinationService, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(tenantsyncevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenantsyncevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(tenantsyncevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(tenantsyncevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(tenantsyncevent.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(tenantsyncevent.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantsyncevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantsyncevent.TenantTable,
			Columns: []string{tenantsyncevent.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantsyncevent.TenantTable,
			Columns: []string{tenantsyncevent.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantsyncevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantSyncEventUpdateOne is the builder for updating a single TenantSyncEvent entity.
type TenantSyncEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantSyncEventMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantSyncEventUpdateOne) SetTenantID(v uuid.UUID) *TenantSyncEventUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantSyncEventUpdateOne) SetNillableTenantID(v *uuid.UUID) *TenantSyncEventUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetDestinationService sets the "destination_service" field.
func (_u *TenantSyncEventUpdateOne) SetDestinationService(v string) *TenantSyncEventUpdateOne {
	_u.mutation.SetDestinationService(v)
	return _u
}

// SetNillableDestinationService sets the "destination_service" field if the given value is not nil.
func (_u *TenantSyncEventUpdateOne) SetNillableDestinationService(v *string) *TenantSyncEventUpdateOne {
	if v != nil {
		_u.SetDestinationService(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *TenantSyncEventUpdateOne) SetPayload(v map[string]interface{}) *TenantSyncEventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantSyncEventUpdateOne) SetStatus(v string) *TenantSyncEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantSyncEventUpdateOne) SetNillableStatus(v *string) *TenantSyncEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *TenantSyncEventUpdateOne) SetAttempts(v int) *TenantSyncEventUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *TenantSyncEventUpdateOne) SetNillableAttempts(v *int) *TenantSyncEventUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *TenantSyncEventUpdateOne) AddAttempts(v int) *TenantSyncEventUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *TenantSyncEventUpdateOne) SetSyncedAt(v time.Time) *TenantSyncEventUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *TenantSyncEventUpdateOne) SetNillableSyncedAt(v *time.Time) *TenantSyncEventUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *TenantSyncEventUpdateOne) ClearSyncedAt() *TenantSyncEventUpdateOne {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantSyncEventUpdateOne) SetUpdatedAt(v time.Time) *TenantSyncEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantSyncEventUpdateOne) SetTenant(v *Tenant) *TenantSyncEventUpdateOne {
	return _u.SetTenantID(v.ID)
}

// Mutation returns the TenantSyncEventMutation object of the builder.
func (_u *TenantSyncEventUpdateOne) Mutation() *TenantSyncEventMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantSyncEventUpdateOne) ClearTenant() *TenantSyncEventUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// Where appends a list predicates to the TenantSyncEventUpdate builder.
func (_u *TenantSyncEventUpdateOne) Where(ps ...predicate.TenantSyncEvent) *TenantSyncEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantSyncEventUpdateOne) Select(field string, fields ...string) *TenantSyncEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantSyncEvent entity.
func (_u *TenantSyncEventUpdateOne) Save(ctx context.Context) (*TenantSyncEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantSyncEventUpdateOne) SaveX(ctx context.Context) *TenantSyncEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantSyncEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantSyncEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantSyncEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantsyncevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantSyncEventUpdateOne) check() error {
	if v, ok := _u.mutation.DestinationService(); ok {
		if err := tenantsyncevent.DestinationServiceValidator(v); err != nil {
			return &ValidationError{Name: "destination_service", err: fmt.Errorf(`ent: validator failed for field "TenantSyncEvent.destination_service": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantSyncEvent.tenant"`)
	}
	return nil
}

func (_u *TenantSyncEventUpdateOne) sqlSave(ctx context.Context) (_node *TenantSyncEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantsyncevent.Table, tenantsyncevent.Columns, sqlgraph.NewFieldSpec(tenantsyncevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantSyncEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantsyncevent.FieldID)
		for _, f := range fields {
			if !tenantsyncevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantsyncevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DestinationService(); ok {
		_spec.SetField(tenantsyncevent.FieldDestinationService, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(tenantsyncevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenantsyncevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(tenantsyncevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(tenantsyncevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(tenantsyncevent.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(tenantsyncevent.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantsyncevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantsyncevent.TenantTable,
			Columns: []string{tenantsyncevent.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantsyncevent.TenantTable,
			Columns: []string{tenantsyncevent.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TenantSyncEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantsyncevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
