// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/ordering-backend/internal/ent/tenant"
	"github.com/bengobox/ordering-backend/internal/ent/tenantsyncevent"
	"github.com/google/uuid"
)

// TenantSyncEvent is the model entity for the TenantSyncEvent schema.
type TenantSyncEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// TenantSlug holds the value of the "tenant_slug" field.
	TenantSlug string `json:"tenant_slug,omitempty"`
	// DestinationService holds the value of the "destination_service" field.
	DestinationService string `json:"destination_service,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt time.Time `json:"synced_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TenantSyncEventQuery when eager-loading is set.
	Edges        TenantSyncEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TenantSyncEventEdges holds the relations/edges for other nodes in the graph.
type TenantSyncEventEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TenantSyncEventEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenantSyncEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenantsyncevent.FieldPayload:
			values[i] = new([]byte)
		case tenantsyncevent.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case tenantsyncevent.FieldTenantSlug, tenantsyncevent.FieldDestinationService, tenantsyncevent.FieldStatus:
			values[i] = new(sql.NullString)
		case tenantsyncevent.FieldSyncedAt, tenantsyncevent.FieldCreatedAt, tenantsyncevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case tenantsyncevent.FieldID, tenantsyncevent.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenantSyncEvent fields.
func (tse *TenantSyncEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenantsyncevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				tse.ID = *value
			}
		case tenantsyncevent.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				tse.TenantID = *value
			}
		case tenantsyncevent.FieldTenantSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_slug", values[i])
			} else if value.Valid {
				tse.TenantSlug = value.String
			}
		case tenantsyncevent.FieldDestinationService:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field destination_service", values[i])
			} else if value.Valid {
				tse.DestinationService = value.String
			}
		case tenantsyncevent.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tse.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case tenantsyncevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				tse.Status = value.String
			}
		case tenantsyncevent.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				tse.Attempts = int(value.Int64)
			}
		case tenantsyncevent.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				tse.SyncedAt = value.Time
			}
		case tenantsyncevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tse.CreatedAt = value.Time
			}
		case tenantsyncevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				tse.UpdatedAt = value.Time
			}
		default:
			tse.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenantSyncEvent.
// This includes values selected through modifiers, order, etc.
func (tse *TenantSyncEvent) Value(name string) (ent.Value, error) {
	return tse.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the TenantSyncEvent entity.
func (tse *TenantSyncEvent) QueryTenant() *TenantQuery {
	return NewTenantSyncEventClient(tse.config).QueryTenant(tse)
}

// Update returns a builder for updating this TenantSyncEvent.
// Note that you need to call TenantSyncEvent.Unwrap() before calling this method if this TenantSyncEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (tse *TenantSyncEvent) Update() *TenantSyncEventUpdateOne {
	return NewTenantSyncEventClient(tse.config).UpdateOne(tse)
}

// Unwrap unwraps the TenantSyncEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tse *TenantSyncEvent) Unwrap() *TenantSyncEvent {
	_tx, ok := tse.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenantSyncEvent is not a transactional entity")
	}
	tse.config.driver = _tx.drv
	return tse
}

// String implements the fmt.Stringer.
func (tse *TenantSyncEvent) String() string {
	var builder strings.Builder
	builder.WriteString("TenantSyncEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tse.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", tse.TenantID))
	builder.WriteString(", ")
	builder.WriteString("tenant_slug=")
	builder.WriteString(tse.TenantSlug)
	builder.WriteString(", ")
	builder.WriteString("destination_service=")
	builder.WriteString(tse.DestinationService)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", tse.Payload))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(tse.Status)
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", tse.Attempts))
	builder.WriteString(", ")
	builder.WriteString("synced_at=")
	builder.WriteString(tse.SyncedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(tse.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(tse.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TenantSyncEvents is a parsable slice of TenantSyncEvent.
type TenantSyncEvents []*TenantSyncEvent
