// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/ordering-backend/internal/ent/predicate"
	"github.com/bengobox/ordering-backend/internal/ent/userfavorite"
)

// UserFavoriteDelete is the builder for deleting a UserFavorite entity.
type UserFavoriteDelete struct {
	config
	hooks    []Hook
	mutation *UserFavoriteMutation
}

// Where appends a list predicates to the UserFavoriteDelete builder.
func (_d *UserFavoriteDelete) Where(ps ...predicate.UserFavorite) *UserFavoriteDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserFavoriteDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserFavoriteDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserFavoriteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userfavorite.Table, sqlgraph.NewFieldSpec(userfavorite.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserFavoriteDeleteOne is the builder for deleting a single UserFavorite entity.
type UserFavoriteDeleteOne struct {
	_d *UserFavoriteDelete
}

// Where appends a list predicates to the UserFavoriteDelete builder.
func (_d *UserFavoriteDeleteOne) Where(ps ...predicate.UserFavorite) *UserFavoriteDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserFavoriteDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userfavorite.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserFavoriteDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
