// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/ordering-backend/internal/ent/user"
	"github.com/bengobox/ordering-backend/internal/ent/userpreference"
	"github.com/google/uuid"
)

// UserPreferenceCreate is the builder for creating a UserPreference entity.
type UserPreferenceCreate struct {
	config
	mutation *UserPreferenceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTheme sets the "theme" field.
func (_c *UserPreferenceCreate) SetTheme(v string) *UserPreferenceCreate {
	_c.mutation.SetTheme(v)
	return _c
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_c *UserPreferenceCreate) SetNillableTheme(v *string) *UserPreferenceCreate {
	if v != nil {
		_c.SetTheme(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *UserPreferenceCreate) SetLanguage(v string) *UserPreferenceCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *UserPreferenceCreate) SetNillableLanguage(v *string) *UserPreferenceCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetNotifyEmail sets the "notify_email" field.
func (_c *UserPreferenceCreate) SetNotifyEmail(v bool) *UserPreferenceCreate {
	_c.mutation.SetNotifyEmail(v)
	return _c
}

// SetNillableNotifyEmail sets the "notify_email" field if the given value is not nil.
func (_c *UserPreferenceCreate) SetNillableNotifyEmail(v *bool) *UserPreferenceCreate {
	if v != nil {
		_c.SetNotifyEmail(*v)
	}
	return _c
}

// SetNotifySms sets the "notify_sms" field.
func (_c *UserPreferenceCreate) SetNotifySms(v bool) *UserPreferenceCreate {
	_c.mutation.SetNotifySms(v)
	return _c
}

// SetNillableNotifySms sets the "notify_sms" field if the given value is not nil.
func (_c *UserPreferenceCreate) SetNillableNotifySms(v *bool) *UserPreferenceCreate {
	if v != nil {
		_c.SetNotifySms(*v)
	}
	return _c
}

// SetNotifyPush sets the "notify_push" field.
func (_c *UserPreferenceCreate) SetNotifyPush(v bool) *UserPreferenceCreate {
	_c.mutation.SetNotifyPush(v)
	return _c
}

// SetNillableNotifyPush sets the "notify_push" field if the given value is not nil.
func (_c *UserPreferenceCreate) SetNillableNotifyPush(v *bool) *UserPreferenceCreate {
	if v != nil {
		_c.SetNotifyPush(*v)
	}
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *UserPreferenceCreate) SetTimezone(v string) *UserPreferenceCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *UserPreferenceCreate) SetNillableTimezone(v *string) *UserPreferenceCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserPreferenceCreate) SetCreatedAt(v time.Time) *UserPreferenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserPreferenceCreate) SetNillableCreatedAt(v *time.Time) *UserPreferenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserPreferenceCreate) SetUpdatedAt(v time.Time) *UserPreferenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserPreferenceCreate) SetNillableUpdatedAt(v *time.Time) *UserPreferenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *UserPreferenceCreate) SetUserID(id uuid.UUID) *UserPreferenceCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *UserPreferenceCreate) SetNillableUserID(id *uuid.UUID) *UserPreferenceCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserPreferenceCreate) SetUser(v *User) *UserPreferenceCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserPreferenceMutation object of the builder.
func (_c *UserPreferenceCreate) Mutation() *UserPreferenceMutation {
	return _c.mutation
}

// Save creates the UserPreference in the database.
func (_c *UserPreferenceCreate) Save(ctx context.Context) (*UserPreference, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPreferenceCreate) SaveX(ctx context.Context) *UserPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPreferenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPreferenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserPreferenceCreate) defaults() {
	if _, ok := _c.mutation.Theme(); !ok {
		v := userpreference.DefaultTheme
		_c.mutation.SetTheme(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := userpreference.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.NotifyEmail(); !ok {
		v := userpreference.DefaultNotifyEmail
		_c.mutation.SetNotifyEmail(v)
	}
	if _, ok := _c.mutation.NotifySms(); !ok {
		v := userpreference.DefaultNotifySms
		_c.mutation.SetNotifySms(v)
	}
	if _, ok := _c.mutation.NotifyPush(); !ok {
		v := userpreference.DefaultNotifyPush
		_c.mutation.SetNotifyPush(v)
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		v := userpreference.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userpreference.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userpreference.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPreferenceCreate) check() error {
	if _, ok := _c.mutation.Theme(); !ok {
		return &ValidationError{Name: "theme", err: errors.New(`ent: missing required field "UserPreference.theme"`)}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "UserPreference.language"`)}
	}
	if _, ok := _c.mutation.NotifyEmail(); !ok {
		return &ValidationError{Name: "notify_email", err: errors.New(`ent: missing required field "UserPreference.notify_email"`)}
	}
	if _, ok := _c.mutation.NotifySms(); !ok {
		return &ValidationError{Name: "notify_sms", err: errors.New(`ent: missing required field "UserPreference.notify_sms"`)}
	}
	if _, ok := _c.mutation.NotifyPush(); !ok {
		return &ValidationError{Name: "notify_push", err: errors.New(`ent: missing required field "UserPreference.notify_push"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "UserPreference.timezone"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserPreference.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserPreference.updated_at"`)}
	}
	return nil
}

func (_c *UserPreferenceCreate) sqlSave(ctx context.Context) (*UserPreference, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPreferenceCreate) createSpec() (*UserPreference, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPreference{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userpreference.Table, sqlgraph.NewFieldSpec(userpreference.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Theme(); ok {
		_spec.SetField(userpreference.FieldTheme, field.TypeString, value)
		_node.Theme = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(userpreference.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.NotifyEmail(); ok {
		_spec.SetField(userpreference.FieldNotifyEmail, field.TypeBool, value)
		_node.NotifyEmail = value
	}
	if value, ok := _c.mutation.NotifySms(); ok {
		_spec.SetField(userpreference.FieldNotifySms, field.TypeBool, value)
		_node.NotifySms = value
	}
	if value, ok := _c.mutation.NotifyPush(); ok {
		_spec.SetField(userpreference.FieldNotifyPush, field.TypeBool, value)
		_node.NotifyPush = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(userpreference.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userpreference.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userpreference.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userpreference.UserTable,
			Columns: []string{userpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_preferences = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserPreference.Create().
//		SetTheme(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserPreferenceUpsert) {
//			SetTheme(v+v).
//		}).
//		Exec(ctx)
func (_c *UserPreferenceCreate) OnConflict(opts ...sql.ConflictOption) *UserPreferenceUpsertOne {
	_c.conflict = opts
	return &UserPreferenceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserPreferenceCreate) OnConflictColumns(columns ...string) *UserPreferenceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserPreferenceUpsertOne{
		create: _c,
	}
}

type (
	// UserPreferenceUpsertOne is the builder for "upsert"-ing
	//  one UserPreference node.
	UserPreferenceUpsertOne struct {
		create *UserPreferenceCreate
	}

	// UserPreferenceUpsert is the "OnConflict" setter.
	UserPreferenceUpsert struct {
		*sql.UpdateSet
	}
)

// SetTheme sets the "theme" field.
func (u *UserPreferenceUpsert) SetTheme(v string) *UserPreferenceUpsert {
	u.Set(userpreference.FieldTheme, v)
	return u
}

// UpdateTheme sets the "theme" field to the value that was provided on create.
func (u *UserPreferenceUpsert) UpdateTheme() *UserPreferenceUpsert {
	u.SetExcluded(userpreference.FieldTheme)
	return u
}

// SetLanguage sets the "language" field.
func (u *UserPreferenceUpsert) SetLanguage(v string) *UserPreferenceUpsert {
	u.Set(userpreference.FieldLanguage, v)
	return u
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *UserPreferenceUpsert) UpdateLanguage() *UserPreferenceUpsert {
	u.SetExcluded(userpreference.FieldLanguage)
	return u
}

// SetNotifyEmail sets the "notify_email" field.
func (u *UserPreferenceUpsert) SetNotifyEmail(v bool) *UserPreferenceUpsert {
	u.Set(userpreference.FieldNotifyEmail, v)
	return u
}

// UpdateNotifyEmail sets the "notify_email" field to the value that was provided on create.
func (u *UserPreferenceUpsert) UpdateNotifyEmail() *UserPreferenceUpsert {
	u.SetExcluded(userpreference.FieldNotifyEmail)
	return u
}

// SetNotifySms sets the "notify_sms" field.
func (u *UserPreferenceUpsert) SetNotifySms(v bool) *UserPreferenceUpsert {
	u.Set(userpreference.FieldNotifySms, v)
	return u
}

// UpdateNotifySms sets the "notify_sms" field to the value that was provided on create.
func (u *UserPreferenceUpsert) UpdateNotifySms() *UserPreferenceUpsert {
	u.SetExcluded(userpreference.FieldNotifySms)
	return u
}

// SetNotifyPush sets the "notify_push" field.
func (u *UserPreferenceUpsert) SetNotifyPush(v bool) *UserPreferenceUpsert {
	u.Set(userpreference.FieldNotifyPush, v)
	return u
}

// UpdateNotifyPush sets the "notify_push" field to the value that was provided on create.
func (u *UserPreferenceUpsert) UpdateNotifyPush() *UserPreferenceUpsert {
	u.SetExcluded(userpreference.FieldNotifyPush)
	return u
}

// SetTimezone sets the "timezone" field.
func (u *UserPreferenceUpsert) SetTimezone(v string) *UserPreferenceUpsert {
	u.Set(userpreference.FieldTimezone, v)
	return u
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *UserPreferenceUpsert) UpdateTimezone() *UserPreferenceUpsert {
	u.SetExcluded(userpreference.FieldTimezone)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserPreferenceUpsert) SetUpdatedAt(v time.Time) *UserPreferenceUpsert {
	u.Set(userpreference.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserPreferenceUpsert) UpdateUpdatedAt() *UserPreferenceUpsert {
	u.SetExcluded(userpreference.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserPreferenceUpsertOne) UpdateNewValues() *UserPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userpreference.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserPreference.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserPreferenceUpsertOne) Ignore() *UserPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserPreferenceUpsertOne) DoNothing() *UserPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserPreferenceCreate.OnConflict
// documentation for more info.
func (u *UserPreferenceUpsertOne) Update(set func(*UserPreferenceUpsert)) *UserPreferenceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetTheme sets the "theme" field.
func (u *UserPreferenceUpsertOne) SetTheme(v string) *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetTheme(v)
	})
}

// UpdateTheme sets the "theme" field to the value that was provided on create.
func (u *UserPreferenceUpsertOne) UpdateTheme() *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateTheme()
	})
}

// SetLanguage sets the "language" field.
func (u *UserPreferenceUpsertOne) SetLanguage(v string) *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *UserPreferenceUpsertOne) UpdateLanguage() *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateLanguage()
	})
}

// SetNotifyEmail sets the "notify_email" field.
func (u *UserPreferenceUpsertOne) SetNotifyEmail(v bool) *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetNotifyEmail(v)
	})
}

// UpdateNotifyEmail sets the "notify_email" field to the value that was provided on create.
func (u *UserPreferenceUpsertOne) UpdateNotifyEmail() *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateNotifyEmail()
	})
}

// SetNotifySms sets the "notify_sms" field.
func (u *UserPreferenceUpsertOne) SetNotifySms(v bool) *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetNotifySms(v)
	})
}

// UpdateNotifySms sets the "notify_sms" field to the value that was provided on create.
func (u *UserPreferenceUpsertOne) UpdateNotifySms() *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateNotifySms()
	})
}

// SetNotifyPush sets the "notify_push" field.
func (u *UserPreferenceUpsertOne) SetNotifyPush(v bool) *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetNotifyPush(v)
	})
}

// UpdateNotifyPush sets the "notify_push" field to the value that was provided on create.
func (u *UserPreferenceUpsertOne) UpdateNotifyPush() *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateNotifyPush()
	})
}

// SetTimezone sets the "timezone" field.
func (u *UserPreferenceUpsertOne) SetTimezone(v string) *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *UserPreferenceUpsertOne) UpdateTimezone() *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateTimezone()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserPreferenceUpsertOne) SetUpdatedAt(v time.Time) *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserPreferenceUpsertOne) UpdateUpdatedAt() *UserPreferenceUpsertOne {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserPreferenceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserPreferenceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserPreferenceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserPreferenceUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserPreferenceUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserPreferenceCreateBulk is the builder for creating many UserPreference entities in bulk.
type UserPreferenceCreateBulk struct {
	config
	err      error
	builders []*UserPreferenceCreate
	conflict []sql.ConflictOption
}

// Save creates the UserPreference entities in the database.
func (_c *UserPreferenceCreateBulk) Save(ctx context.Context) ([]*UserPreference, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPreference, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPreferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPreferenceCreateBulk) SaveX(ctx context.Context) []*UserPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPreferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPreferenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserPreference.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserPreferenceUpsert) {
//			SetTheme(v+v).
//		}).
//		Exec(ctx)
func (_c *UserPreferenceCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserPreferenceUpsertBulk {
	_c.conflict = opts
	return &UserPreferenceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserPreference.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserPreferenceCreateBulk) OnConflictColumns(columns ...string) *UserPreferenceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserPreferenceUpsertBulk{
		create: _c,
	}
}

// UserPreferenceUpsertBulk is the builder for "upsert"-ing
// a bulk of UserPreference nodes.
type UserPreferenceUpsertBulk struct {
	create *UserPreferenceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserPreference.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserPreferenceUpsertBulk) UpdateNewValues() *UserPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userpreference.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserPreference.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserPreferenceUpsertBulk) Ignore() *UserPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserPreferenceUpsertBulk) DoNothing() *UserPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserPreferenceCreateBulk.OnConflict
// documentation for more info.
func (u *UserPreferenceUpsertBulk) Update(set func(*UserPreferenceUpsert)) *UserPreferenceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserPreferenceUpsert{UpdateSet: update})
	}))
	return u
}

// SetTheme sets the "theme" field.
func (u *UserPreferenceUpsertBulk) SetTheme(v string) *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetTheme(v)
	})
}

// UpdateTheme sets the "theme" field to the value that was provided on create.
func (u *UserPreferenceUpsertBulk) UpdateTheme() *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateTheme()
	})
}

// SetLanguage sets the "language" field.
func (u *UserPreferenceUpsertBulk) SetLanguage(v string) *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *UserPreferenceUpsertBulk) UpdateLanguage() *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateLanguage()
	})
}

// SetNotifyEmail sets the "notify_email" field.
func (u *UserPreferenceUpsertBulk) SetNotifyEmail(v bool) *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetNotifyEmail(v)
	})
}

// UpdateNotifyEmail sets the "notify_email" field to the value that was provided on create.
func (u *UserPreferenceUpsertBulk) UpdateNotifyEmail() *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateNotifyEmail()
	})
}

// SetNotifySms sets the "notify_sms" field.
func (u *UserPreferenceUpsertBulk) SetNotifySms(v bool) *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetNotifySms(v)
	})
}

// UpdateNotifySms sets the "notify_sms" field to the value that was provided on create.
func (u *UserPreferenceUpsertBulk) UpdateNotifySms() *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateNotifySms()
	})
}

// SetNotifyPush sets the "notify_push" field.
func (u *UserPreferenceUpsertBulk) SetNotifyPush(v bool) *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetNotifyPush(v)
	})
}

// UpdateNotifyPush sets the "notify_push" field to the value that was provided on create.
func (u *UserPreferenceUpsertBulk) UpdateNotifyPush() *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateNotifyPush()
	})
}

// SetTimezone sets the "timezone" field.
func (u *UserPreferenceUpsertBulk) SetTimezone(v string) *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *UserPreferenceUpsertBulk) UpdateTimezone() *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateTimezone()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserPreferenceUpsertBulk) SetUpdatedAt(v time.Time) *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserPreferenceUpsertBulk) UpdateUpdatedAt() *UserPreferenceUpsertBulk {
	return u.Update(func(s *UserPreferenceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserPreferenceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserPreferenceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserPreferenceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserPreferenceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
