// Code generated by ent, DO NOT EDIT.

package customeraddress

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/ordering-backend/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldTenantID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldUserID, v))
}

// AddressLine1 applies equality check predicate on the "address_line1" field. It's identical to AddressLine1EQ.
func AddressLine1(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldAddressLine1, v))
}

// AddressLine2 applies equality check predicate on the "address_line2" field. It's identical to AddressLine2EQ.
func AddressLine2(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldAddressLine2, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCity, v))
}

// County applies equality check predicate on the "county" field. It's identical to CountyEQ.
func County(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCounty, v))
}

// PostalCode applies equality check predicate on the "postal_code" field. It's identical to PostalCodeEQ.
func PostalCode(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldPostalCode, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCountry, v))
}

// Latitude applies equality check predicate on the "latitude" field. It's identical to LatitudeEQ.
func Latitude(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldLatitude, v))
}

// Longitude applies equality check predicate on the "longitude" field. It's identical to LongitudeEQ.
func Longitude(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldLongitude, v))
}

// PlusCode applies equality check predicate on the "plus_code" field. It's identical to PlusCodeEQ.
func PlusCode(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldPlusCode, v))
}

// Instructions applies equality check predicate on the "instructions" field. It's identical to InstructionsEQ.
func Instructions(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldInstructions, v))
}

// ContactName applies equality check predicate on the "contact_name" field. It's identical to ContactNameEQ.
func ContactName(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldContactName, v))
}

// ContactPhone applies equality check predicate on the "contact_phone" field. It's identical to ContactPhoneEQ.
func ContactPhone(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldContactPhone, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldIsDefault, v))
}

// IsVerified applies equality check predicate on the "is_verified" field. It's identical to IsVerifiedEQ.
func IsVerified(v bool) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldIsVerified, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldTenantID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldUserID, vs...))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldLabel, v))
}

// AddressLine1EQ applies the EQ predicate on the "address_line1" field.
func AddressLine1EQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldAddressLine1, v))
}

// AddressLine1NEQ applies the NEQ predicate on the "address_line1" field.
func AddressLine1NEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldAddressLine1, v))
}

// AddressLine1In applies the In predicate on the "address_line1" field.
func AddressLine1In(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldAddressLine1, vs...))
}

// AddressLine1NotIn applies the NotIn predicate on the "address_line1" field.
func AddressLine1NotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldAddressLine1, vs...))
}

// AddressLine1GT applies the GT predicate on the "address_line1" field.
func AddressLine1GT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldAddressLine1, v))
}

// AddressLine1GTE applies the GTE predicate on the "address_line1" field.
func AddressLine1GTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldAddressLine1, v))
}

// AddressLine1LT applies the LT predicate on the "address_line1" field.
func AddressLine1LT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldAddressLine1, v))
}

// AddressLine1LTE applies the LTE predicate on the "address_line1" field.
func AddressLine1LTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldAddressLine1, v))
}

// AddressLine1Contains applies the Contains predicate on the "address_line1" field.
func AddressLine1Contains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldAddressLine1, v))
}

// AddressLine1HasPrefix applies the HasPrefix predicate on the "address_line1" field.
func AddressLine1HasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldAddressLine1, v))
}

// AddressLine1HasSuffix applies the HasSuffix predicate on the "address_line1" field.
func AddressLine1HasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldAddressLine1, v))
}

// AddressLine1EqualFold applies the EqualFold predicate on the "address_line1" field.
func AddressLine1EqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldAddressLine1, v))
}

// AddressLine1ContainsFold applies the ContainsFold predicate on the "address_line1" field.
func AddressLine1ContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldAddressLine1, v))
}

// AddressLine2EQ applies the EQ predicate on the "address_line2" field.
func AddressLine2EQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldAddressLine2, v))
}

// AddressLine2NEQ applies the NEQ predicate on the "address_line2" field.
func AddressLine2NEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldAddressLine2, v))
}

// AddressLine2In applies the In predicate on the "address_line2" field.
func AddressLine2In(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldAddressLine2, vs...))
}

// AddressLine2NotIn applies the NotIn predicate on the "address_line2" field.
func AddressLine2NotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldAddressLine2, vs...))
}

// AddressLine2GT applies the GT predicate on the "address_line2" field.
func AddressLine2GT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldAddressLine2, v))
}

// AddressLine2GTE applies the GTE predicate on the "address_line2" field.
func AddressLine2GTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldAddressLine2, v))
}

// AddressLine2LT applies the LT predicate on the "address_line2" field.
func AddressLine2LT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldAddressLine2, v))
}

// AddressLine2LTE applies the LTE predicate on the "address_line2" field.
func AddressLine2LTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldAddressLine2, v))
}

// AddressLine2Contains applies the Contains predicate on the "address_line2" field.
func AddressLine2Contains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldAddressLine2, v))
}

// AddressLine2HasPrefix applies the HasPrefix predicate on the "address_line2" field.
func AddressLine2HasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldAddressLine2, v))
}

// AddressLine2HasSuffix applies the HasSuffix predicate on the "address_line2" field.
func AddressLine2HasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldAddressLine2, v))
}

// AddressLine2IsNil applies the IsNil predicate on the "address_line2" field.
func AddressLine2IsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldAddressLine2))
}

// AddressLine2NotNil applies the NotNil predicate on the "address_line2" field.
func AddressLine2NotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldAddressLine2))
}

// AddressLine2EqualFold applies the EqualFold predicate on the "address_line2" field.
func AddressLine2EqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldAddressLine2, v))
}

// AddressLine2ContainsFold applies the ContainsFold predicate on the "address_line2" field.
func AddressLine2ContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldAddressLine2, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldCity, v))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldCity, v))
}

// CountyEQ applies the EQ predicate on the "county" field.
func CountyEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCounty, v))
}

// CountyNEQ applies the NEQ predicate on the "county" field.
func CountyNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldCounty, v))
}

// CountyIn applies the In predicate on the "county" field.
func CountyIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldCounty, vs...))
}

// CountyNotIn applies the NotIn predicate on the "county" field.
func CountyNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldCounty, vs...))
}

// CountyGT applies the GT predicate on the "county" field.
func CountyGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldCounty, v))
}

// CountyGTE applies the GTE predicate on the "county" field.
func CountyGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldCounty, v))
}

// CountyLT applies the LT predicate on the "county" field.
func CountyLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldCounty, v))
}

// CountyLTE applies the LTE predicate on the "county" field.
func CountyLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldCounty, v))
}

// CountyContains applies the Contains predicate on the "county" field.
func CountyContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldCounty, v))
}

// CountyHasPrefix applies the HasPrefix predicate on the "county" field.
func CountyHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldCounty, v))
}

// CountyHasSuffix applies the HasSuffix predicate on the "county" field.
func CountyHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldCounty, v))
}

// CountyIsNil applies the IsNil predicate on the "county" field.
func CountyIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldCounty))
}

// CountyNotNil applies the NotNil predicate on the "county" field.
func CountyNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldCounty))
}

// CountyEqualFold applies the EqualFold predicate on the "county" field.
func CountyEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldCounty, v))
}

// CountyContainsFold applies the ContainsFold predicate on the "county" field.
func CountyContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldCounty, v))
}

// PostalCodeEQ applies the EQ predicate on the "postal_code" field.
func PostalCodeEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldPostalCode, v))
}

// PostalCodeNEQ applies the NEQ predicate on the "postal_code" field.
func PostalCodeNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldPostalCode, v))
}

// PostalCodeIn applies the In predicate on the "postal_code" field.
func PostalCodeIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldPostalCode, vs...))
}

// PostalCodeNotIn applies the NotIn predicate on the "postal_code" field.
func PostalCodeNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldPostalCode, vs...))
}

// PostalCodeGT applies the GT predicate on the "postal_code" field.
func PostalCodeGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldPostalCode, v))
}

// PostalCodeGTE applies the GTE predicate on the "postal_code" field.
func PostalCodeGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldPostalCode, v))
}

// PostalCodeLT applies the LT predicate on the "postal_code" field.
func PostalCodeLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldPostalCode, v))
}

// PostalCodeLTE applies the LTE predicate on the "postal_code" field.
func PostalCodeLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldPostalCode, v))
}

// PostalCodeContains applies the Contains predicate on the "postal_code" field.
func PostalCodeContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldPostalCode, v))
}

// PostalCodeHasPrefix applies the HasPrefix predicate on the "postal_code" field.
func PostalCodeHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldPostalCode, v))
}

// PostalCodeHasSuffix applies the HasSuffix predicate on the "postal_code" field.
func PostalCodeHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldPostalCode, v))
}

// PostalCodeIsNil applies the IsNil predicate on the "postal_code" field.
func PostalCodeIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldPostalCode))
}

// PostalCodeNotNil applies the NotNil predicate on the "postal_code" field.
func PostalCodeNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldPostalCode))
}

// PostalCodeEqualFold applies the EqualFold predicate on the "postal_code" field.
func PostalCodeEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldPostalCode, v))
}

// PostalCodeContainsFold applies the ContainsFold predicate on the "postal_code" field.
func PostalCodeContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldPostalCode, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldCountry, v))
}

// LatitudeEQ applies the EQ predicate on the "latitude" field.
func LatitudeEQ(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldLatitude, v))
}

// LatitudeNEQ applies the NEQ predicate on the "latitude" field.
func LatitudeNEQ(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldLatitude, v))
}

// LatitudeIn applies the In predicate on the "latitude" field.
func LatitudeIn(vs ...float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldLatitude, vs...))
}

// LatitudeNotIn applies the NotIn predicate on the "latitude" field.
func LatitudeNotIn(vs ...float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldLatitude, vs...))
}

// LatitudeGT applies the GT predicate on the "latitude" field.
func LatitudeGT(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldLatitude, v))
}

// LatitudeGTE applies the GTE predicate on the "latitude" field.
func LatitudeGTE(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldLatitude, v))
}

// LatitudeLT applies the LT predicate on the "latitude" field.
func LatitudeLT(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldLatitude, v))
}

// LatitudeLTE applies the LTE predicate on the "latitude" field.
func LatitudeLTE(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldLatitude, v))
}

// LatitudeIsNil applies the IsNil predicate on the "latitude" field.
func LatitudeIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldLatitude))
}

// LatitudeNotNil applies the NotNil predicate on the "latitude" field.
func LatitudeNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldLatitude))
}

// LongitudeEQ applies the EQ predicate on the "longitude" field.
func LongitudeEQ(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldLongitude, v))
}

// LongitudeNEQ applies the NEQ predicate on the "longitude" field.
func LongitudeNEQ(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldLongitude, v))
}

// LongitudeIn applies the In predicate on the "longitude" field.
func LongitudeIn(vs ...float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldLongitude, vs...))
}

// LongitudeNotIn applies the NotIn predicate on the "longitude" field.
func LongitudeNotIn(vs ...float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldLongitude, vs...))
}

// LongitudeGT applies the GT predicate on the "longitude" field.
func LongitudeGT(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldLongitude, v))
}

// LongitudeGTE applies the GTE predicate on the "longitude" field.
func LongitudeGTE(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldLongitude, v))
}

// LongitudeLT applies the LT predicate on the "longitude" field.
func LongitudeLT(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldLongitude, v))
}

// LongitudeLTE applies the LTE predicate on the "longitude" field.
func LongitudeLTE(v float64) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldLongitude, v))
}

// LongitudeIsNil applies the IsNil predicate on the "longitude" field.
func LongitudeIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldLongitude))
}

// LongitudeNotNil applies the NotNil predicate on the "longitude" field.
func LongitudeNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldLongitude))
}

// PlusCodeEQ applies the EQ predicate on the "plus_code" field.
func PlusCodeEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldPlusCode, v))
}

// PlusCodeNEQ applies the NEQ predicate on the "plus_code" field.
func PlusCodeNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldPlusCode, v))
}

// PlusCodeIn applies the In predicate on the "plus_code" field.
func PlusCodeIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldPlusCode, vs...))
}

// PlusCodeNotIn applies the NotIn predicate on the "plus_code" field.
func PlusCodeNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldPlusCode, vs...))
}

// PlusCodeGT applies the GT predicate on the "plus_code" field.
func PlusCodeGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldPlusCode, v))
}

// PlusCodeGTE applies the GTE predicate on the "plus_code" field.
func PlusCodeGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldPlusCode, v))
}

// PlusCodeLT applies the LT predicate on the "plus_code" field.
func PlusCodeLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldPlusCode, v))
}

// PlusCodeLTE applies the LTE predicate on the "plus_code" field.
func PlusCodeLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldPlusCode, v))
}

// PlusCodeContains applies the Contains predicate on the "plus_code" field.
func PlusCodeContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldPlusCode, v))
}

// PlusCodeHasPrefix applies the HasPrefix predicate on the "plus_code" field.
func PlusCodeHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldPlusCode, v))
}

// PlusCodeHasSuffix applies the HasSuffix predicate on the "plus_code" field.
func PlusCodeHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldPlusCode, v))
}

// PlusCodeIsNil applies the IsNil predicate on the "plus_code" field.
func PlusCodeIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldPlusCode))
}

// PlusCodeNotNil applies the NotNil predicate on the "plus_code" field.
func PlusCodeNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldPlusCode))
}

// PlusCodeEqualFold applies the EqualFold predicate on the "plus_code" field.
func PlusCodeEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldPlusCode, v))
}

// PlusCodeContainsFold applies the ContainsFold predicate on the "plus_code" field.
func PlusCodeContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldPlusCode, v))
}

// InstructionsEQ applies the EQ predicate on the "instructions" field.
func InstructionsEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldInstructions, v))
}

// InstructionsNEQ applies the NEQ predicate on the "instructions" field.
func InstructionsNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldInstructions, v))
}

// InstructionsIn applies the In predicate on the "instructions" field.
func InstructionsIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldInstructions, vs...))
}

// InstructionsNotIn applies the NotIn predicate on the "instructions" field.
func InstructionsNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldInstructions, vs...))
}

// InstructionsGT applies the GT predicate on the "instructions" field.
func InstructionsGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldInstructions, v))
}

// InstructionsGTE applies the GTE predicate on the "instructions" field.
func InstructionsGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldInstructions, v))
}

// InstructionsLT applies the LT predicate on the "instructions" field.
func InstructionsLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldInstructions, v))
}

// InstructionsLTE applies the LTE predicate on the "instructions" field.
func InstructionsLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldInstructions, v))
}

// InstructionsContains applies the Contains predicate on the "instructions" field.
func InstructionsContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldInstructions, v))
}

// InstructionsHasPrefix applies the HasPrefix predicate on the "instructions" field.
func InstructionsHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldInstructions, v))
}

// InstructionsHasSuffix applies the HasSuffix predicate on the "instructions" field.
func InstructionsHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldInstructions, v))
}

// InstructionsIsNil applies the IsNil predicate on the "instructions" field.
func InstructionsIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldInstructions))
}

// InstructionsNotNil applies the NotNil predicate on the "instructions" field.
func InstructionsNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldInstructions))
}

// InstructionsEqualFold applies the EqualFold predicate on the "instructions" field.
func InstructionsEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldInstructions, v))
}

// InstructionsContainsFold applies the ContainsFold predicate on the "instructions" field.
func InstructionsContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldInstructions, v))
}

// ContactNameEQ applies the EQ predicate on the "contact_name" field.
func ContactNameEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldContactName, v))
}

// ContactNameNEQ applies the NEQ predicate on the "contact_name" field.
func ContactNameNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldContactName, v))
}

// ContactNameIn applies the In predicate on the "contact_name" field.
func ContactNameIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldContactName, vs...))
}

// ContactNameNotIn applies the NotIn predicate on the "contact_name" field.
func ContactNameNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldContactName, vs...))
}

// ContactNameGT applies the GT predicate on the "contact_name" field.
func ContactNameGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldContactName, v))
}

// ContactNameGTE applies the GTE predicate on the "contact_name" field.
func ContactNameGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldContactName, v))
}

// ContactNameLT applies the LT predicate on the "contact_name" field.
func ContactNameLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldContactName, v))
}

// ContactNameLTE applies the LTE predicate on the "contact_name" field.
func ContactNameLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldContactName, v))
}

// ContactNameContains applies the Contains predicate on the "contact_name" field.
func ContactNameContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldContactName, v))
}

// ContactNameHasPrefix applies the HasPrefix predicate on the "contact_name" field.
func ContactNameHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldContactName, v))
}

// ContactNameHasSuffix applies the HasSuffix predicate on the "contact_name" field.
func ContactNameHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldContactName, v))
}

// ContactNameIsNil applies the IsNil predicate on the "contact_name" field.
func ContactNameIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldContactName))
}

// ContactNameNotNil applies the NotNil predicate on the "contact_name" field.
func ContactNameNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldContactName))
}

// ContactNameEqualFold applies the EqualFold predicate on the "contact_name" field.
func ContactNameEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldContactName, v))
}

// ContactNameContainsFold applies the ContainsFold predicate on the "contact_name" field.
func ContactNameContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldContactName, v))
}

// ContactPhoneEQ applies the EQ predicate on the "contact_phone" field.
func ContactPhoneEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldContactPhone, v))
}

// ContactPhoneNEQ applies the NEQ predicate on the "contact_phone" field.
func ContactPhoneNEQ(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldContactPhone, v))
}

// ContactPhoneIn applies the In predicate on the "contact_phone" field.
func ContactPhoneIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldContactPhone, vs...))
}

// ContactPhoneNotIn applies the NotIn predicate on the "contact_phone" field.
func ContactPhoneNotIn(vs ...string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldContactPhone, vs...))
}

// ContactPhoneGT applies the GT predicate on the "contact_phone" field.
func ContactPhoneGT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldContactPhone, v))
}

// ContactPhoneGTE applies the GTE predicate on the "contact_phone" field.
func ContactPhoneGTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldContactPhone, v))
}

// ContactPhoneLT applies the LT predicate on the "contact_phone" field.
func ContactPhoneLT(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldContactPhone, v))
}

// ContactPhoneLTE applies the LTE predicate on the "contact_phone" field.
func ContactPhoneLTE(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldContactPhone, v))
}

// ContactPhoneContains applies the Contains predicate on the "contact_phone" field.
func ContactPhoneContains(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContains(FieldContactPhone, v))
}

// ContactPhoneHasPrefix applies the HasPrefix predicate on the "contact_phone" field.
func ContactPhoneHasPrefix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasPrefix(FieldContactPhone, v))
}

// ContactPhoneHasSuffix applies the HasSuffix predicate on the "contact_phone" field.
func ContactPhoneHasSuffix(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldHasSuffix(FieldContactPhone, v))
}

// ContactPhoneIsNil applies the IsNil predicate on the "contact_phone" field.
func ContactPhoneIsNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIsNull(FieldContactPhone))
}

// ContactPhoneNotNil applies the NotNil predicate on the "contact_phone" field.
func ContactPhoneNotNil() predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotNull(FieldContactPhone))
}

// ContactPhoneEqualFold applies the EqualFold predicate on the "contact_phone" field.
func ContactPhoneEqualFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEqualFold(FieldContactPhone, v))
}

// ContactPhoneContainsFold applies the ContainsFold predicate on the "contact_phone" field.
func ContactPhoneContainsFold(v string) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldContainsFold(FieldContactPhone, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldIsDefault, v))
}

// IsVerifiedEQ applies the EQ predicate on the "is_verified" field.
func IsVerifiedEQ(v bool) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldIsVerified, v))
}

// IsVerifiedNEQ applies the NEQ predicate on the "is_verified" field.
func IsVerifiedNEQ(v bool) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldIsVerified, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CustomerAddress {
	return predicate.CustomerAddress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CustomerAddress {
	return predicate.CustomerAddress(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrders applies the HasEdge predicate on the "orders" edge.
func HasOrders() predicate.CustomerAddress {
	return predicate.CustomerAddress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrdersWith applies the HasEdge predicate on the "orders" edge with a given conditions (other predicates).
func HasOrdersWith(preds ...predicate.Order) predicate.CustomerAddress {
	return predicate.CustomerAddress(func(s *sql.Selector) {
		step := newOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomerAddress) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomerAddress) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomerAddress) predicate.CustomerAddress {
	return predicate.CustomerAddress(sql.NotPredicates(p))
}
