// Code generated by ent, DO NOT EDIT.

package menuitemasset

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the menuitemasset type in the database.
	Label = "menu_item_asset"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMenuItemID holds the string denoting the menu_item_id field in the database.
	FieldMenuItemID = "menu_item_id"
	// FieldAssetType holds the string denoting the asset_type field in the database.
	FieldAssetType = "asset_type"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldDisplayOrder holds the string denoting the display_order field in the database.
	FieldDisplayOrder = "display_order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeMenuItem holds the string denoting the menu_item edge name in mutations.
	EdgeMenuItem = "menu_item"
	// Table holds the table name of the menuitemasset in the database.
	Table = "menu_item_assets"
	// MenuItemTable is the table that holds the menu_item relation/edge.
	MenuItemTable = "menu_item_assets"
	// MenuItemInverseTable is the table name for the MenuItem entity.
	// It exists in this package in order to avoid circular dependency with the "menuitem" package.
	MenuItemInverseTable = "menu_items"
	// MenuItemColumn is the table column denoting the menu_item relation/edge.
	MenuItemColumn = "menu_item_id"
)

// Columns holds all SQL columns for menuitemasset fields.
var Columns = []string{
	FieldID,
	FieldMenuItemID,
	FieldAssetType,
	FieldURL,
	FieldMetadata,
	FieldDisplayOrder,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AssetTypeValidator is a validator for the "asset_type" field. It is called by the builders before save.
	AssetTypeValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultDisplayOrder holds the default value on creation for the "display_order" field.
	DefaultDisplayOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the MenuItemAsset queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMenuItemID orders the results by the menu_item_id field.
func ByMenuItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMenuItemID, opts...).ToFunc()
}

// ByAssetType orders the results by the asset_type field.
func ByAssetType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssetType, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByDisplayOrder orders the results by the display_order field.
func ByDisplayOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByMenuItemField orders the results by menu_item field.
func ByMenuItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMenuItemStep(), sql.OrderByField(field, opts...))
	}
}
func newMenuItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MenuItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MenuItemTable, MenuItemColumn),
	)
}
