apiVersion: v1
kind: Secret
metadata:
  name: ordering-backend-env
  namespace: ordering
type: Opaque
stringData:
  ORDERING_APP_ENV: "Production"
  ORDERING_POSTGRES_URL: "postgres://postgres:postgres@postgresql.ordering.svc.cluster.local:5432/ordering?sslmode=disable"
  ORDERING_REDIS_ADDR: "redis-master.ordering.svc.cluster.local:6379"
  ORDERING_NATS_URL: "nats://nats.messaging.svc.cluster.local:4222"
  ORDERING_NATS_STREAM: "ordering"
  ORDERING_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4317"
  ORDERING_AUTH_SERVICE_URL: "https://sso.codevertexitsolutions.com"
  ORDERING_AUTH_ISSUER: "https://sso.codevertexitsolutions.com"
  ORDERING_AUTH_AUDIENCE: "codevertex"
  ORDERING_AUTH_JWKS_URL: "https://sso.codevertexitsolutions.com/api/v1/.well-known/jwks.json"
  ORDERING_AUTH_ENABLE_API_KEY_AUTH: "true"
